### ISSUE TITLE
[Bug] HUD does not render

### ISSUE THREAD

**Issue by obj-obj** [MeteorDevelopment/meteor-client#1031]
**Describe the bug**

**To Reproduce**
1. Launch minecraft with meteor and sodium
2. Open a world and the HUD does not render

**Expected behavior**
HUD elements render (armor, fps, enabled modules)

**Additional context**
Minecraft 1.16.5
HUD elements still render if you open options on the main menu, but stop rendering upon entering a world
This error is in the log:
```log
[14:00:47] [main/WARN]: Mixin apply failed meteor-client-sodium.mixins.json:SodiumFluidRendererMixin -> me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on meteor-client-sodium.mixins.json:SodiumFluidRendererMixin->@Inject::onCalculateQuadColors(Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadViewMutable;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> Inject -> meteor-client-sodium.mixins.json:SodiumFluidRendererMixin->@Inject::onCalculateQuadColors(Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on meteor-client-sodium.mixins.json:SodiumFluidRendererMixin->@Inject::onCalculateQuadColors(Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadViewMutable;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [ -> Inject -> meteor-client-sodium.mixins.json:SodiumFluidRendererMixin->@Inject::onCalculateQuadColors(Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/light/LightPipeline;Lnet/minecraft/class_2350;FZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879) [?:1.8.0_292]
	at me.jellysquid.mods.sodium.client.render.pipeline.context.ChunkRenderContext.<init>(ChunkRenderContext.java:34) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.startWorkers(ChunkBuilder.java:93) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.init(ChunkBuilder.java:221) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.<init>(ChunkRenderManager.java:93) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:248) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setWorld(SodiumWorldRenderer.java:108) [sodium-fabric-mc1.16.3-0.1.0.jar:?]
	at net.minecraft.class_761.handler$zzc000$onWorldChanged(class_761.java:3129) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_761.method_3244(class_761.java:744) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java:2049) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:1974) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:382) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:110) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:18) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_2600$$Lambda$5426/0x0000000000000000.run(Unknown Source) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
```

**Comment by obj-obj** [comment]
Only mods are meteor, sodium, and fabric API

**Comment by obj-obj** [comment]
This happens even without sodium installed, there are no errors in the log

**Comment by obj-obj** [comment]
Hmmm resetting my HUD positions fixed it, my config was probably just fucked up

**Comment by Tiebe** [comment]
How did you reset your HUD position, I have the same issue

**Comment by Tiebe** [comment]
@obj-obj
