### ISSUE TITLE
Not find llibdiscord-rpc.so

### ISSUE THREAD

**Issue by N08I40K** [MeteorDevelopment/meteor-client#116]
Hello, I am using Ubuntu 20.04.1 LTS x64. When connecting to any server or local world, Minecraft crashes with the following error:
"The game crashed whilst unexpected error
Error: java.lang.UnsatisfiedLinkError: Can't load library: /home/n08i40k/.discord-rpc/libdiscord-rpc.so
Completion code: 255 "

**Comment by N08I40K** [comment]
Full crash log:
---- Minecraft Crash Report ----
// You're mean.

Time: 06.01.21 19:23
Description: Unexpected error

java.lang.UnsatisfiedLinkError: Can't load library: /home/n08i40k/.discord-rpc/libdiscord-rpc.so
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at minegame159.meteorclient.modules.misc.DiscordPresence.onActivate(DiscordPresence.java:79)
	at minegame159.meteorclient.modules.ModuleManager.lambda$new$5(ModuleManager.java:188)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.class_634.handler$zbe000$onGameJoin(class_634.java:3448)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at minegame159.meteorclient.modules.misc.DiscordPresence.onActivate(DiscordPresence.java:79)
	at minegame159.meteorclient.modules.ModuleManager.lambda$new$5(ModuleManager.java:188)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.class_634.handler$zbe000$onGameJoin(class_634.java:3448)
	at net.minecraft.class_634.method_11120(class_634.java:411)
	at net.minecraft.class_2678.method_11567(class_2678.java:110)
	at net.minecraft.class_2678.method_11054(class_2678.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)

-- Affected level --
Details:
	All players: 1 total; [class_746['X_N08I40K_X'/40631, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 18225, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.0-58-generic
	Java Version: 1.8.0_275, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 2871926752 bytes (2738 MB) / 3456106496 bytes (3296 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 2
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.29.2+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+552549d53a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fabritone: Fabritone 1.6.2
		meteor-client: Meteor Client 0.3.8
		minecraft: Minecraft 1.16.4
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa DRI Intel(R) HD Graphics (BYT) GL version 3.0 Mesa 20.0.8, Intel Open Source Technology Center
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: Русский (Россия)
	CPU: 2x Intel(R) Celeron(R) CPU J1800 @ 2.41GHz

-- Meteor Client --
Version: 0.3.8

[Misc]:
Discord Presence (discord-presence)

**Comment by Clashbestie** [comment]
If you really want to play you could clone the repository, wipe the global vars, onActivate(), onDeactivate() and the EventHandler, from [DiscordPresence.java](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/minegame159/meteorclient/modules/misc/DiscordPresence.java) and make your own build. If your lucky this causes the client to no longer try to load the libdiscord-rpc.so, until the bug is fixed

**Comment by N08I40K** [comment]
> If you really want to play you could clone the repository, wipe the global vars, onActivate(), onDeactivate() and the EventHandler, from [DiscordPresence.java](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/minegame159/meteorclient/modules/misc/DiscordPresence.java) and make your own build. If your lucky this causes the client to no longer try to load the libdiscord-rpc.so, until the bug is fixed

Thanks for the advice! But I did it before writing about this error.

**Comment by RedCarlos26** [comment]
Is this still a bug, or it is fixed?

**Comment by MineGame159** [comment]
@N08I40K Does this still happe?

**Comment by N08I40K** [comment]
> @N08I40K Does this still happe?

No, now everything works. Thanks.
