### ISSUE TITLE
Doing CTRL+V into spam text bar crashes teh client

### ISSUE THREAD

**Issue by ShibaGG** [MeteorDevelopment/meteor-client#1316]
rip

**Comment by StormyBytes** [comment]
Can you provide more information? Stating "rip" doesnt tell us much.

**Comment by ShibaGG** [comment]
well, idk how to put screenshots or whatever

**Comment by StormyBytes** [comment]
> well, idk how to put screenshots or whatever

If you cant provide more information, how do you expect us to find the problem or help you in any way?

**Comment by ShibaGG** [comment]
just, try it idflk

**Comment by StormyBytes** [comment]
> just, try it idflk

It works fine on my end, so idk what you are talking about

**Comment by ShibaGG** [comment]
im using 1.17.1 client

**Comment by ShibaGG** [comment]
idk why but i wanna play minecraft with u

**Comment by StormyBytes** [comment]
Jesus christ just send the crash report.

**Comment by ShibaGG** [comment]
nah its ok

**Comment by ShibaGG** [comment]
but i wanna play minecraft with u
idk why

**Comment by StormyBytes** [comment]
Send the crash report.

**Comment by ShibaGG** [comment]
I mean, why?

**Comment by ShibaGG** [comment]
nvm sending it

**Comment by ShibaGG** [comment]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 30.07.21 6:25
Description: keyPressed event handler

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at meteordevelopment.meteorclient.settings.StringListSetting.lambda$fillTable$0(StringListSetting.java:83)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.runAction(WTextBox.java:465)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.onKeyRepeated(WTextBox.java:221)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.onKeyPressed(WTextBox.java:185)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.keyPressed(WWidget.java:112)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25404(WidgetScreen.java:166)
	at net.minecraft.class_309.method_1454(class_309.java:374)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at meteordevelopment.meteorclient.settings.StringListSetting.lambda$fillTable$0(StringListSetting.java:83)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.runAction(WTextBox.java:465)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.onKeyRepeated(WTextBox.java:221)
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.onKeyPressed(WTextBox.java:185)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.keyPressed(WWidget.java:112)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.keyPressed(WContainer.java:171)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25404(WidgetScreen.java:166)
	at net.minecraft.class_309.method_1454(class_309.java:374)

-- Affected screen --
Details:
	Screen name: meteordevelopment.meteorclient.gui.screens.ModuleScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)

-- Affected level --
Details:
	All players: 1 total; [class_746['MaryBabel'/2588452, l='ClientLevel', x=-286.84, y=70.00, z=320.70]]
	Chunk stats: 121, 49
	Level dimension: minecraft:overworld
	Level spawn location: World: (-283,256,-215), Section: (at 5,0,9 in -18,16,-14; chunk contains blocks -288,0,-224 to -273,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 17251 game time, 0 day time
	Server brand: 1b1t
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1092682824 bytes (1042 MiB) / 1744830464 bytes (1664 MiB) up to 1744830464 bytes (1664 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
	Identifier: Intel64 Family 6 Model 30 Stepping 5
	Microarchitecture: Nehalem (Client) / Nehalem (Server)
	Frequency (GHz): 3,41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 560 Ti  
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x1200
	Graphics card #0 versionInfo: DriverVersion=10.18.13.5362
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: SDRAM
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: SDRAM
	Virtual memory max (MB): 20698,17
	Virtual memory used (MB): 18722,97
	Swap memory total (MB): 12515,05
	Swap memory used (MB): 5162,07
	JVM Flags: 10 total; -Xmn128M -Xmx1646M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.7.0
		fabric: Fabric API 0.37.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		java: OpenJDK 64-Bit Server VM 16
		meteor-client: Meteor Client 0.4.5
		minecraft: Minecraft 1.17.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 560 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 353.62, NVIDIA Corporation
	Window size: 1280x1002
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5 CPU 750 @ 2.67GHz

-- Meteor Client --
Version: 0.4.5

[Combat]:
Auto Totem (auto-totem)
Bow Aimbot (Bow Aimbot)
Criticals (criticals)
Crystal Aura (crystal-aura)

[Player]:
Auto Eat (auto-eat)
Auto Respawn (auto-respawn)
Portals (portals)
Reach (reach)

[Movement]:
Anchor (anchor)
Boat Fly (boat-fly)
Elytra Boost (elytra-boost)
Elytra Fly (elytra-fly)
Entity Speed (entity-speed)
No Fall (no-fall)
No Slow (no-slow)
Velocity (velocity)

[Render]:
Break Indicators (break-indicators)
Entity Owner (entity-owner)
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Hole Esp (hole-esp)
No Render (no-render)
Storage Esp (storage-esp)
Time Changer (time-changer)
Tracers (tracers)
Void Esp (void-esp)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Notifier (notifier)
Packet Canceller (packet-canceller)
Vanilla Spoof (vanilla-spoof)

**Comment by necrophili** [comment]
Lmfao this thread

**Comment by RedCarlos26** [comment]
True
