### ISSUE TITLE
[Bug] Crash on configuring HUD in main menu

### ISSUE THREAD

**Issue by Paul1365972** [MeteorDevelopment/meteor-client#1359]
1. Be in main menu
2. Open ClickGUI
3. Choose HUD
4. Crash

Minecraft 1.17.1
Meteor 0.4.6

```
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_23317()" because "meteordevelopment.meteorclient.utils.Utils.mc.field_1724" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.34)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.distanceTo(PlayerUtils.java:243)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getFadeAlpha(ESP.java:176)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.getOutlineColor(ESP.java:205)
	at meteordevelopment.meteorclient.systems.modules.render.ESP.shouldDrawOutline(ESP.java:199)
	at net.minecraft.entity.Entity.handler$bco000$isInvisibleToCanceller(Entity:11072)
	at net.minecraft.entity.Entity.isInvisibleTo(Entity)
	at net.minecraft.client.render.entity.LivingEntityRenderer.hasLabel(LivingEntityRenderer:256)
	at net.minecraft.client.render.entity.LivingEntityRenderer.hasLabel(LivingEntityRenderer:29)
	at net.minecraft.client.render.entity.EntityRenderer.render(EntityRenderer:68)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:144)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:64)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:42)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen:154)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem:1119)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen:154)
	at meteordevelopment.meteorclient.systems.modules.render.hud.modules.PlayerModelHud.render(PlayerModelHud.java:109)
	at meteordevelopment.meteorclient.systems.modules.render.hud.HUD.onRender(HUD.java:161)
	at meteordevelopment.meteorclient.gui.tabs.builtin.HudTab$HudScreen.render(HudTab.java:283)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:874)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
...
[Render]:
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Logout Spots (logout-spots)
Nametags (nametags)
Storage Esp (storage-esp)
Tracers (tracers)
...
```

**Comment by MineGame159** [comment]
Fixed in 24f7697788c7a64159b1d9ea50f281d13b808e83
