### ISSUE TITLE
Alt Tab crashes the game.

### ISSUE THREAD

**Issue by deprale** [MeteorDevelopment/meteor-client#1366]
**Describe the bug**
Crash to desktop Exit error 0

**To Reproduce**
Go on any server
Alt tab.
Profit.

**Expected behavior**
Alt tab with no crash?

**Screenshots**
No need
**Additional context**
1.17.1 dev and stable meteor client both crash.

NOTE: Pressing ESC (going into menu) before alt tabbing, will not crash the game.

Log:

```
> ---- Minecraft Crash Report ----
> // Why did you do that?
> 
> Time: 13/08/2021, 04:44
> Description: Unexpected error
> 
> java.lang.ClassCastException: class java.lang.Double cannot be cast to class net.minecraft.class_746 (java.lang.Double is in module java.base of loader 'bootstrap'; net.minecraft.class_746 is in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1c33c17b)
> 	at org.spongepowered.asm.synthetic.args.Args$7.set(Args$7.java)
> 	at net.minecraft.class_312.args$bng000$modifyLookDirection(class_312.java:3106)
> 	at net.minecraft.class_312.method_1606(class_312.java:266)
> 	at net.minecraft.class_310.method_1523(class_310.java:1086)
> 	at net.minecraft.class_310.method_1514(class_310.java:728)
> 	at net.minecraft.client.main.Main.main(Main.java:217)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at org.spongepowered.asm.synthetic.args.Args$7.set(Args$7.java)
> 	at net.minecraft.class_312.args$bng000$modifyLookDirection(class_312.java:3106)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['yanderezaza'/1152981, l='ClientLevel', x=92785.30, y=7.00, z=65478.30]]
> 	Chunk stats: 1024, 529
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (192,70,-175), Section: (at 0,6,1 in 12,4,-11; chunk contains blocks 192,0,-176 to 207,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
> 	Level time: 153092 game time, 14402228 day time
> 	Server brand: Waterfall <- Paper
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:370)
> 	at net.minecraft.class_310.method_1587(class_310.java:2399)
> 	at net.minecraft.class_310.method_1514(class_310.java:752)
> 	at net.minecraft.client.main.Main.main(Main.java:217)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 
> -- Last reload --
> Details:
> 	Reload number: 1
> 	Reload reason: initial
> 	Finished: Yes
> 	Packs: Default, Fabric Mods
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.17.1
> 	Minecraft Version ID: 1.17.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 16.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 341783232 bytes (325 MiB) / 973078528 bytes (928 MiB) up to 2147483648 bytes (2048 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.60
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: NVIDIA GeForce RTX 2060
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x1f08
> 	Graphics card #0 versionInfo: DriverVersion=27.21.14.5730
> 	Memory slot #0 capacity (MB): 8192.00
> 	Memory slot #0 clockSpeed (GHz): 3.00
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 8192.00
> 	Memory slot #1 clockSpeed (GHz): 3.00
> 	Memory slot #1 type: DDR4
> 	Memory slot #2 capacity (MB): 8192.00
> 	Memory slot #2 clockSpeed (GHz): 3.00
> 	Memory slot #2 type: DDR4
> 	Memory slot #3 capacity (MB): 8192.00
> 	Memory slot #3 clockSpeed (GHz): 3.00
> 	Memory slot #3 type: DDR4
> 	Virtual memory max (MB): 37557.72
> 	Virtual memory used (MB): 10476.03
> 	Swap memory total (MB): 4864.00
> 	Swap memory used (MB): 0.00
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		advanced-xray-fabric: Advanced XRay (Fabric) 0.6.0-build.8
> 		amecsapi: Amecs API 1.1.4+mc21w16a
> 		architectury: Architectury 2.3.24
> 		authme: Auth Me 1.5.0
> 		autofish: Autofish 0.9.3
> 		baritone: Baritone 1.7.0
> 		betterf3: BetterF3 1.1.5
> 		blue_endless_jankson: jankson 1.2.1
> 		caelus: Caelus API 0.0.16-1.17
> 		cardinal-components-base: Cardinal Components API (base) 3.0.0
> 		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-config2: Cloth Config v5 5.0.38
> 		com_moandjiezana_toml_toml4j: toml4j 0.7.2
> 		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
> 		diggusmaximus: Diggus Maximus 1.4.5-1.17
> 		dynamicfps: Dynamic FPS 2.0.5
> 		dynmus: Dynamic Music 1.3.1
> 		elytratrinket: Elytra Trinket 2.0.1-1.17
> 		enchantmentdescriptions: Enchantment Descriptions 4.0.1
> 		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
> 		entityculling: EntityCulling-Fabric 1.3.3
> 		fabric: Fabric API 0.37.2+1.17
> 		fabric-api-base: Fabric API Base 0.3.0+a02b446313
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
> 		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
> 		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
> 		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
> 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
> 		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
> 		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
> 		fabricloader: Fabric Loader 0.11.6
> 		fatxporbs: Fat Experience Orbs 1.0.1
> 		ferritecore: FerriteCore 3.0.1
> 		fiber: fiber 0.23.0-2
> 		fiber2cloth: Fiber To Cloth 3.2.0
> 		harvest: Harvest 1.2.12
> 		horsestatsvanilla: Horse Stats Vanilla 4.1.8
> 		hydrogen: Hydrogen 0.3
> 		illuminations: Illuminations 1.6.3
> 		inmis: Inmis 2.3.1-1.17
> 		inventorysorter: Inventory Sorter 1.7.9-1.17
> 		iris: Iris 1.1.1
> 		jankson: Jankson 3.0.1+j1.2.0
> 		java: OpenJDK 64-Bit Server VM 16
> 		krypton: Krypton 0.1.4
> 		kyrptconfig: Kytpt Config 1.1.10-1.17
> 		lazydfu: LazyDFU 0.1.2
> 		libgui: LibGui 4.0.0-beta.4+1.17-rc1
> 		libninepatch: LibNinePatch 1.1.0
> 		libzoomer: LibZoomer 0.2.1+1.17
> 		lithium: Lithium 0.7.3
> 		meteor-client: Meteor Client 0.4.6-1200
> 		minecraft: Minecraft 1.17.1
> 		mm: Manningham Mills 2.2
> 		modmenu: Mod Menu 2.0.4
> 		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
> 		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
> 		omega-config: OmegaConfig 1.0.4
> 		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
> 		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
> 		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
> 		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
> 		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
> 		smootherbedrock: Smoother Bedrock 1.0.1
> 		sodium: Sodium 0.3.0+IRIS2
> 		spruceui: SpruceUI 3.2.0+1.17
> 		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
> 		trinketofundying: Trinket of Undying 2.0.0-1.17
> 		trinkets: Trinkets 3.0.2
> 		tweed: Tweed 3.0.0-beta.26
> 		voxelmap: VoxelMap 1.10.15
> 		wthit: wthit 3.8.1
> 	Launched Version: fabric-loader-0.11.6-1.17.1
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 457.30, NVIDIA Corporation
> 	Window size: 854x480
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: vanilla, Fabric Mods
> 	Current Language: English (US)
> 	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
> 
> -- Meteor Client --
> Version: 0.4.6
> Dev Build: 1200
> 
> [Misc]:
> Discord Presence (discord-presence)
```

**Comment by deprale** [comment]
> 		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17

Is the culprit, I had alt bound to zoom!
