### ISSUE TITLE
Game crashes when activating the mount bypass dupe

### ISSUE THREAD

**Issue by Jor-1** [MeteorDevelopment/meteor-client#1418]
I added a chest to a donkey and rode it, then I activated the mount bypass dupe button and my game crashed.

**To Reproduce**
1. Go to a Minecraft realms server
2. Ride a tamed donkey with a chest and stuff inside (no saddle using entity control)
3.  Click the mount bypass dupe button (from addon)

**Expected behavior**
To dupe the items.

**Crash Report**
---- Minecraft Crash Report ----
// Don't do that.

Time: 28/8/21, 1:02 pm
Description: mouseReleased event handler

meteordevelopment.orbit.NoLambdaFactoryException: No registered lambda listener for 'meteordevelopment.addons.mbd.AutoMountBypassDupe'.
	at meteordevelopment.orbit.EventBus.getLambdaFactory(EventBus.java:182)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:160)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.subscribe(EventBus.java:71)
	at meteordevelopment.meteorclient.systems.modules.Module.toggle(Module.java:69)
	at meteordevelopment.meteorclient.gui.themes.meteor.widgets.WMeteorModule.onPressed(WMeteorModule.java:58)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:119)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.orbit.EventBus.getLambdaFactory(EventBus.java:182)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:160)
	at meteordevelopment.orbit.EventBus.lambda$getListeners$2(EventBus.java:140)
	at meteordevelopment.orbit.EventBus.getListeners(EventBus.java:152)
	at meteordevelopment.orbit.EventBus.subscribe(EventBus.java:71)
	at meteordevelopment.meteorclient.systems.modules.Module.toggle(Module.java:69)
	at meteordevelopment.meteorclient.gui.themes.meteor.widgets.WMeteorModule.onPressed(WMeteorModule.java:58)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:138)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:119)
	at net.minecraft.class_312.method_1605(class_312.java:96)

-- Affected screen --
Details:
	Screen name: meteordevelopment.meteorclient.gui.screens.ModulesScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jor___'/31413, l='ClientLevel', x=-50.24, y=63.53, z=2401.85]]
	Chunk stats: 1024, 399
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,63,0), Section: (at 0,15,0 in 12,3,0; chunk contains blocks 192,0,0 to 207,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1956222 game time, 7311 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, cullleaves/smartleaves, 1.17, OreGrids-Faithful

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1246822328 bytes (1189 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8853
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 17931.78
	Virtual memory used (MB): 14551.10
	Swap memory total (MB): 10413.62
	Swap memory used (MB): 3020.89
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 2.4.25
		baritone: Baritone 1.7.0
		bookdupe-addon: Meteor Book Dupe Addon 0.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		cullleaves: Cull Leaves 2.2.0
		dynamicfps: Dynamic FPS 2.0.5
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.38.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+3fe74aa118
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.0+3fe74aa118
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+8195aec118
		fabricloader: Fabric Loader 0.11.6
		ferritecore: FerriteCore 3.0.1
		hydrogen: Hydrogen 0.3
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lithium: Lithium 0.7.3
		meteor-client: Meteor Client 0.4.6-1207
		meteor-mbd-addon: Meteor MBD Addon 0.3
		minecraft: Minecraft 1.17.1
		multiconnect: MultiConnect 1.4.12
		multiconnect-api: MultiConnect API 1.4.12
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.8853, Intel
	Window size: 1920x1201
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 1374266
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, cullleaves/smartleaves, file/1.17, file/OreGrids-Faithful
	Current Language: English (Australia)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

-- Meteor Client --
Version: 0.4.6
Dev Build: 1207

[Player]:
Anti Hunger (anti-hunger)
Auto Replenish (auto-replenish)
Auto Respawn (auto-respawn)
No Break Delay (no-break-delay)
Portals (portals)
Potion Saver (potion-saver)

[Movement]:
Air Jump (air-jump)
Anti Levitation (anti-levitation)
Anti Void (anti-void)
Elytra Boost (elytra-boost)
Entity Control (entity-control)
No Fall (no-fall)
Velocity (velocity)

[Render]:
Better Tooltips (better-tooltips)
Block Selection (block-selection)
Blur (blur)
Boss Stack (boss-stack)
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Item Highlight (item-highlight)
Item Physics (item-physics)
Logout Spots (logout-spots)
Nametags (nametags)
No Render (no-render)
Trajectories (trajectories)
Unfocused Cpu (unfocused-cpu)
Waypoints (waypoints)

[World]:
Anti Cactus (anti-cactus)
Build Height (build-height)

[Misc]:
Auto Mount Bypass Dupe (auto-mount-bypass-dupe)
Better Chat (better-chat)
Better Tab (better-tab)
Inventory Tweaks (inventory-tweaks)
Middle Click Friend (middle-click-friend)
Notifier (notifier)
Vanilla Spoof (vanilla-spoof)

**Additional context**
Mods being used
![image](https://user-images.githubusercontent.com/85599827/131208029-d93ffeda-807a-406b-8578-1c01796bf351.png)

**Comment by StormyBytes** [comment]
That addon is archived and wont be updated or fixed
