### ISSUE TITLE
[Bug] Error executing task on Client

### ISSUE THREAD

**Issue by Farel-cyber** [MeteorDevelopment/meteor-client#1480]
### Describe the bug

I'm using minecraft 1.17.1 with sodium and lithium. and when I add the meteor client and fabric-api to my minecraft my minecraft fps is very small around 10 fps, usually when I don't use the meteor client it can be more than 100 fps

**_And this is the error i found in my log_**
```
[17:13:39] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'collideRule_-118'.
	at net.minecraft.class_269.method_1157(class_269.java:237) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2081) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_5900.method_34173(class_5900.java:130) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_5900.method_11054(class_5900.java:15) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

### Steps to reproduce

```bash
1. when i use meteor client my fps goes down
2. and if i don't use meteor client my fps is high
```

### Meteor Version

meteor-client-0.4.5

### Minecraft Version

Minecraft 1.17.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
- [X] This is a valid bug and I have checked all settings.

**Comment by MineGame159** [comment]
That error has nothing to do with Meteor and we are not experiencing any performance difference with and without Meteor (no modules enabled).

**Comment by MineGame159** [comment]
Provide 2 [spark](https://modrinth.com/mod/spark) profiles, one with Meteor and one without Meteor atleast 10 seconds long.

**Comment by Farel-cyber** [comment]
I can't use spark because my minecraft version is 1.17.1 and spark version is 1.16.5

**Comment by MineGame159** [comment]
Spark is for 1.17.1 too
