### ISSUE TITLE
[Bug] Autogap crash

### ISSUE THREAD

**Issue by LordDoom-eng** [MeteorDevelopment/meteor-client#1503]
### Describe the bug

crash report
---- Minecraft Crash Report ----
// There are four lights!

Time: 13/09/21 13:20
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Module.isActive()" because "module" is null
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.startEating(AutoGap.java:187)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.onTick(AutoGap.java:167)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zgc000$onPreTick(class_310.java:6602)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.startEating(AutoGap.java:187)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.onTick(AutoGap.java:167)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zgc000$onPreTick(class_310.java:6602)

-- Affected level --
Details:
	All players: 2 total; [class_746['_LordDoom_'/29, l='ClientLevel', x=8.70, y=4.00, z=-11.43], class_745['Aikla'/2757, l='ClientLevel', x=3.70, y=4.00, z=-10.36]]
	Chunk stats: 256, 99
	Level dimension: minecraft:the_nether
	Level spawn location: World: (8,4,8), Section: (at 8,4,8 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2133478 game time, 712945939 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Bare_Bones_1.17_Doom, cool.zip, §4§l§o§kaaa§6§l§oCustomTotem§a1.16.2§4§l§o§kaaa.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 914495544 bytes (872 MiB) / 1811939328 bytes (1728 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A6-4400M APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: AMD Radeon HD 7520G
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x9990
	Graphics card #0 versionInfo: DriverVersion=15.200.1065.0
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 10914.32
	Virtual memory used (MB): 9622.96
	Swap memory total (MB): 3264.06
	Swap memory used (MB): 508.56
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.3-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7520G GL version 3.2.13399 Core Profile Forward-Compatible Context 15.200.1065.0, ATI Technologies Inc.
	Window size: 1366x715
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/Bare_Bones_1.17_Doom, file/cool.zip (incompatible), file/§4§l§o§kaaa§6§l§oCustomTotem§a1.16.2§4§l§o§kaaa.zip (incompatible), Fabric Mods
	Current Language: English (US)
	CPU: 2x AMD A6-4400M APU with Radeon(tm) HD Graphics 
	Player Count: 2 / 8; [class_3222['_LordDoom_'/29, l='ServerLevel[pvp]', x=8.70, y=4.00, z=-11.43], class_3222['Aikla'/2757, l='ServerLevel[pvp]', x=3.70, y=4.00, z=-10.36]]
	Data Packs: vanilla (incompatible), file/oldmechanic-v1-0.zip (incompatible)

-- Meteor Client --
Version: 0.4.6
Dev Build: 1254

[Combat]:
Auto Armor (auto-armor)
Auto Totem (auto-totem)
Criticals (criticals)
Offhand (offhand)

[Player]:
Auto Gap (auto-gap)
Fast Use (fast-use)
No Break Delay (no-break-delay)
No Mining Trace (no-mining-trace)
Reach (reach)
Speed Mine (speed-mine)

[Movement]:
Velocity (velocity)

[Render]:
Block Selection (block-selection)
Camera Tweaks (camera-tweaks)
Chams (chams)
Esp (esp)
HUD (HUD)
Hand View (hand-view)
Item Physics (item-physics)
Nametags (nametags)
No Render (no-render)
Tracers (tracers)
Unfocused Cpu (unfocused-cpu)

[Misc]:
Better Tab (better-tab)

[Banana+ Combat]:
Anchor+ (anchor+)
City Esp+ (city-esp+)
Surround+ (surround+)

### Steps to reproduce

```bash
yesterday the same thing happened in meteor pvp doing tests.

another player with autogap (regeneration) while the other player uses ca or another module.
```

### Meteor Version

meteor-client-0.4.6-1254

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
Could you show your mods folder

**Comment by LordDoom-eng** [comment]
![image](https://user-images.githubusercontent.com/73355762/133173843-8d120cbe-4bf8-4404-a117-4090b8dc05b4.png)

I generally use this, but testing on instances with orion causes the crash. lel
when running autogap.

@GhostTypes

**Comment by GhostTypes** [comment]
You don't even have any Orion modules enabled

**Comment by LordDoom-eng** [comment]
> You don't even have any Orion modules enabled or even have it loaded

I thought it was another mod, and only use the ones in the photo, then add orion and when they hurt you when executing autogap the game crashes.

**Comment by GhostTypes** [comment]
I cannot reproduce the crash. Open a bug report on the Orion GitHub with a crash log from Orion or I cant help

**Comment by ecstaticpanic** [comment]
can confirm reproducibility of the unexpected error of autogap module when below health threshold on osx monterey with latest dev gradle build of meteor 0.4.7 and with latest stable release of orion 0.1; i will open an issue in orion repository now

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Module.isActive()" because "module" is null
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.startEating(AutoGap.java:187)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap.onTick(AutoGap.java:167)
	at meteordevelopment.meteorclient.systems.modules.player.AutoGap$$Lambda$6545/0x000000001c591688.accept(Unknown Source)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zki000$onPreTick(class_310.java:4600)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
