### ISSUE TITLE
[Bug] Shulker box inventory sort crash

### ISSUE THREAD

**Issue by bainchild** [MeteorDevelopment/meteor-client#1568]
### Describe the bug

If you try to sort inventory while peeking into a shulker box with middle mouse click , it crashes

https://user-images.githubusercontent.com/55368789/136493684-67cabfb1-89b0-4dbc-80b3-dd5e3a484341.mp4

```
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:294) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_636.method_2906(class_636.java:417) ~[intermediary-fabric-1.17.1.jar:?]
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.click(InvUtils.java:259) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.run(InvUtils.java:236) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.toId(InvUtils.java:180) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.meteorclient.utils.player.InventorySorter.tick(InventorySorter.java:58) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.meteorclient.systems.modules.misc.InventoryTweaks.onTickPre(InventoryTweaks.java:207) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.4.6-1287.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47) ~[meteor-client-0.4.6-1287.jar:?]
	at net.minecraft.class_310.handler$zpe000$onPreTick(class_310.java:12106) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 52 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java:394) ~[intermediary-fabric-1.17.1.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:284) ~[intermediary-fabric-1.17.1.jar:?]
	... 20 more
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/7/21, 10:22 PM
Description: Container click

java.lang.IndexOutOfBoundsException: Index 52 out of bounds for length 46
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:284)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.click(InvUtils.java:259)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.run(InvUtils.java:236)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.toId(InvUtils.java:180)
	at meteordevelopment.meteorclient.utils.player.InventorySorter.tick(InventorySorter.java:58)
	at meteordevelopment.meteorclient.systems.modules.misc.InventoryTweaks.onTickPre(InventoryTweaks.java:207)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zpe000$onPreTick(class_310.java:12106)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)

-- Click info --
Details:
	Menu Type: <no type>
	Menu Class: net.minecraft.class_1723
	Slot Count: 46
	Slot: 52
	Button: 0
	Type: PICKUP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:284)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.click(InvUtils.java:259)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.run(InvUtils.java:236)
	at meteordevelopment.meteorclient.utils.player.InvUtils$Action.toId(InvUtils.java:180)
	at meteordevelopment.meteorclient.utils.player.InventorySorter.tick(InventorySorter.java:58)
	at meteordevelopment.meteorclient.systems.modules.misc.InventoryTweaks.onTickPre(InventoryTweaks.java:207)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zpe000$onPreTick(class_310.java:12106)

-- Affected level --
Details:
	All players: 1 total; [class_746['-----------'/189, l='ClientLevel', x=-13.63, y=70.00, z=37.47]]
	Chunk stats: 225, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (6,72,2), Section: (at 6,8,2 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6879 game time, 6879 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.10.0-____-amd64
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1621672520 bytes (1546 MiB) / 2734686208 bytes (2608 MiB) up to 2734686208 bytes (2608 MiB)
	CPUs: 4
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4897.71
	Virtual memory used (MB): 7204.26
	Swap memory total (MB): 976.00
	Swap memory used (MB): 185.06
	Fabric Mods: 
                    ---
	Launched Version: fabric-1.17.1
	Window size: 1360x709
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	Player Count: 1 / 8; [class_3222['---------'/189, l='ServerLevel[crash show]', x=-13.63, y=70.00, z=37.47]]
	Data Packs: vanilla, Fabric Mods

-- Meteor Client --
Version: 0.4.6
Dev Build: 1287

[Render]:
Better Tooltips (better-tooltips)

[Misc]:
Better Chat (better-chat)
Better Tab (better-tab)
Inventory Tweaks (inventory-tweaks)
Vanilla Spoof (vanilla-spoof)
```

### Steps to reproduce

```bash
1. open inventory
2. peek into shulker box using middle mouse button
3. try to sort inventory using middle mouse button with inventory tweaks on
```

### Meteor Version

0.4.6 1287

### Minecraft Version

1.17.1

### Operating System

Linux 64 bit , debian

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 1d84fe228bd14402081b43e94d7d566e9f34a436.
