### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by titusj3026** [MeteorDevelopment/meteor-client#1768]
### Describe the bug

Whenever I try to launch minecraft It crashes with stacktrace: 
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.17.1 with any version between 1.18-alpha.21.37.a (inclusive) and 1.19- (exclusive).
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
		 - 'OpenJDK 64-Bit Server VM' (java) 16 is an environment reference and usually requires installation or launcher changes to adjust
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires any version between 1.18-alpha.21.37.a (inclusive) and 1.19- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'OpenJDK 64-Bit Server VM' (java) 16, reason: to replace
	 - 'Minecraft' (minecraft) 1.17.1, reason: to replace
	 - mod 'Baritone' (baritone) 1.7.0, reason: unknown
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.17.1 with any version between 1.18-alpha.21.37.a (inclusive) and 1.19- (exclusive).
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 16 with version 17 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 16!
		 - 'OpenJDK 64-Bit Server VM' (java) 16 is an environment reference and usually requires installation or launcher changes to adjust
	 - Mod 'Fabric API' (fabric) 0.44.0+1.18 requires any version between 1.18-alpha.21.37.a (inclusive) and 1.19- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!
		 - 'Minecraft' (minecraft) 1.17.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - 'OpenJDK 64-Bit Server VM' (java) 16, reason: to replace
	 - 'Minecraft' (minecraft) 1.17.1, reason: to replace
	 - mod 'Baritone' (baritone) 1.7.0, reason: unknown
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more

### Steps to reproduce

```bash
I launched minecraft
```

### Meteor Version

1.17.1

### Minecraft Version

0.4.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by titusj3026** [comment]
nevermind resolved.
