### ISSUE TITLE
[Bug] 1.18 Crash

### ISSUE THREAD

**Issue by EurekaEffect** [MeteorDevelopment/meteor-client#1769]
### Describe the bug

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 06.12.2021, 23:36
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because the return value of "net.minecraft.class_2378.method_10221(Object)" is null
	at meteordevelopment.meteorclient.settings.ParticleTypeListSetting.toTag(ParticleTypeListSetting.java:66)
	at meteordevelopment.meteorclient.settings.SettingGroup.toTag(SettingGroup.java:54)
	at meteordevelopment.meteorclient.utils.misc.NbtUtils.listToTag(NbtUtils.java:26)
	at meteordevelopment.meteorclient.settings.Settings.toTag(Settings.java:117)
	at meteordevelopment.meteorclient.systems.modules.Module.toTag(Module.java:129)
	at meteordevelopment.meteorclient.systems.modules.Modules.toTag(Modules.java:300)
	at meteordevelopment.meteorclient.systems.System.save(System.java:35)
	at meteordevelopment.meteorclient.systems.Systems.save(Systems.java:72)
	at meteordevelopment.meteorclient.systems.Systems.save(Systems.java:78)
	at meteordevelopment.meteorclient.systems.Systems.onGameLeft(Systems.java:65)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zfb000$onDisconnect(class_310.java:7546)
	at net.minecraft.class_310.method_18096(class_310.java)
	at net.minecraft.class_310.method_18099(class_310.java:2185)
	at net.minecraft.class_433.method_19836(class_433.java:79)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:200)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.settings.ParticleTypeListSetting.toTag(ParticleTypeListSetting.java:66)
	at meteordevelopment.meteorclient.settings.SettingGroup.toTag(SettingGroup.java:54)
	at meteordevelopment.meteorclient.utils.misc.NbtUtils.listToTag(NbtUtils.java:26)
	at meteordevelopment.meteorclient.settings.Settings.toTag(Settings.java:117)
	at meteordevelopment.meteorclient.systems.modules.Module.toTag(Module.java:129)
	at meteordevelopment.meteorclient.systems.modules.Modules.toTag(Modules.java:300)
	at meteordevelopment.meteorclient.systems.System.save(System.java:35)
	at meteordevelopment.meteorclient.systems.Systems.save(Systems.java:72)
	at meteordevelopment.meteorclient.systems.Systems.save(Systems.java:78)
	at meteordevelopment.meteorclient.systems.Systems.onGameLeft(Systems.java:65)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$zfb000$onDisconnect(class_310.java:7546)
	at net.minecraft.class_310.method_18096(class_310.java)
	at net.minecraft.class_310.method_18099(class_310.java:2185)
	at net.minecraft.class_433.method_19836(class_433.java:79)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:200)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_433
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:200)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 3 total; [class_746['EurekaEffect'/110691, l='ClientLevel', x=-455577.41, y=64.00, z=800374.24], class_745['ZeRoL20'/127143, l='ClientLevel', x=-455576.33, y=63.56, z=800373.60], class_745['AndreDePivo'/53365, l='ClientLevel', x=-455556.97, y=67.00, z=800367.87]]
	Chunk stats: 1024, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,64,224), Section: (at 0,0,0 in 6,4,14; chunk contains blocks 96,0,224 to 111,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2441 game time, 4084013 day time
	Server brand: BotFilter (git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:616ea7a:unknown) <- §6EasyGrief§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Programmer Art, osshepack_v2.1.zip

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 531910512 bytes (507 MiB) / 1811939328 bytes (1728 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2,30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8729
	Graphics card #1 name: NVIDIA GeForce MX110
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048,00
	Graphics card #1 deviceId: 0x174e
	Graphics card #1 versionInfo: DriverVersion=27.21.14.6627
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 16293,22
	Virtual memory used (MB): 10889,26
	Swap memory total (MB): 8192,00
	Swap memory used (MB): 0,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.8-1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce MX110/PCIe/SSE2 GL version 3.2.0 NVIDIA 466.27, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, programer_art, file/osshepack_v2.1.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz

-- Meteor Client --
Version: 0.4.7
Dev Build: 1361

[Combat]:
Auto Totem (auto-totem)
Kill Aura (kill-aura)

[Player]:
Air Place (air-place)
Auto Replenish (auto-replenish)
Fast Use (fast-use)
No Mining Trace (no-mining-trace)
No Rotate (no-rotate)

[Movement]:
Anchor (anchor)
Velocity (velocity)

[Render]:
Fullbright (fullbright)
HUD (HUD)
Hand View (hand-view)
Hole Esp (hole-esp)
Item Highlight (item-highlight)
Nametags (nametags)
No Render (no-render)
Pop Chams (pop-chams)

[Misc]:
Notifier (notifier)

### Steps to reproduce

```bash
Logged out from the server
```

### Meteor Version

v0.4.7 build #1361

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
Delete your meteor-client folder, I think it's a profile corruption issue

**Comment by CrystalCL** [comment]
Lmao
