### ISSUE TITLE
[Bug] Game won't launch on 1.18 (Exit code 0)

### ISSUE THREAD

**Issue by tankirules** [MeteorDevelopment/meteor-client#1775]
### Describe the bug

I have no other mods, and minecraft won't launch.
Log below:
[17:00:42] [main/INFO]: Loading for game Minecraft 1.18
[17:00:42] [main/INFO]: Loading 4 mods:
	- fabricloader 0.12.8
	- java 17
	- meteor-client 0.4.6
	- minecraft 1.18
[17:00:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Daniel_2/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[17:00:42] [main/INFO]: Compatibility level set to JAVA_16
[17:00:43] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand)
[17:00:43] [main/WARN]: @Mixin target baritone.command.defaults.ComeCommand was not found meteor-client-baritone.mixins.json:ComeCommandMixin
[17:00:43] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/client/indigo/renderer/render/AbstractQuadRenderer)
[17:00:43] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer was not found meteor-client-indigo.mixins.json:AbstractQuadRendererMixin
[17:00:43] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext (java.lang.ClassNotFoundException: net/fabricmc/fabric/impl/client/indigo/renderer/render/TerrainRenderContext)
[17:00:43] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext was not found meteor-client-indigo.mixins.json:TerrainRenderContextMixin
[17:00:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/model/light/data/LightDataAccess (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/model/light/data/LightDataAccess)
[17:00:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.model.light.data.LightDataAccess was not found meteor-client-sodium.mixins.json:LightDataAccessMixin
[17:00:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/occlusion/BlockOcclusionCache)
[17:00:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.occlusion.BlockOcclusionCache was not found meteor-client-sodium.mixins.json:SodiumBlockOcculsionCacheMixin
[17:00:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer)
[17:00:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer was not found meteor-client-sodium.mixins.json:SodiumBlockRendererMixin
[17:00:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/pipeline/FluidRenderer)
[17:00:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer was not found meteor-client-sodium.mixins.json:SodiumFluidRendererMixin
[17:00:43] [main/WARN]: Error loading class: grondag/canvas/render/world/CanvasWorldRenderer (java.lang.ClassNotFoundException: grondag/canvas/render/world/CanvasWorldRenderer)
[17:00:43] [main/WARN]: @Mixin target grondag.canvas.render.world.CanvasWorldRenderer was not found meteor-client-canvas.mixins.json:CanvasWorldRendererMixin
[17:00:43] [main/WARN]: Error loading class: net/minecraft/class_638$class_6234 (java.lang.ClassNotFoundException: net/minecraft/class_638$class_6234)
[17:00:48] [main/ERROR]: Mixin apply for mod meteor-client failed meteor-client.mixins.json:WorldChunkAccessor -> net.minecraft.class_2818: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_12854:Ljava/util/Map; in net/minecraft/class_2818 for meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map; [INJECT Applicator Phase -> meteor-client.mixins.json:WorldChunkAccessor -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_12854:Ljava/util/Map; in net/minecraft/class_2818 for meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map; [INJECT Applicator Phase -> meteor-client.mixins.json:WorldChunkAccessor -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1408) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) [meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) [intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
[17:00:48] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) ~[meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2818 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) ~[meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) ~[meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [meteor-client.mixins.json:WorldChunkAccessor] from phase [DEFAULT] in config [meteor-client.mixins.json] from mod [meteor-client] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) ~[meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_12854:Ljava/util/Map; in net/minecraft/class_2818 for meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map; [INJECT Applicator Phase -> meteor-client.mixins.json:WorldChunkAccessor -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:WorldChunkAccessor->@Accessor[FIELD_GETTER]::getBlockEntities()Ljava/util/Map;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1408) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6802.<clinit>(class_6802.java:17) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:56) ~[meteor-client-0.4.6.jar:?]
	at net.minecraft.class_128.handler$zbo000$onAddStackTrace(class_128.java:524) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[fabric-loader-0.12.8-1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) ~[fabric-loader-0.12.8.jar:?]
	... 2 more

### Steps to reproduce

```bash
I just try to launch minecraft with meteor client fabric installed, and it insta crashes with "Exit code 0"
```

### Meteor Version

0.4.6

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Update to latest dev build.
