### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ColGroLoOl** [MeteorDevelopment/meteor-client#1795]
### Describe the bug

Minecraft starts like normal, but as soon as it tries to start discord rich presence, it crashes.
Dunno why or what caused it, worked perfectly fine 10min ago

Log:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/14/21, 6:38 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.misc.DiscordPresence.toggle()" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get(java.lang.Class)" is null
	at meteordevelopment.meteorclient.MeteorClient.lambda$onInitializeClient$1(MeteorClient.java:70)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:85)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:92)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:90)
	at net.minecraft.client.MinecraftClient.handler$zei004$onInit(MinecraftClient.java:4014)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:637)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

### Steps to reproduce

```bash
Run the client without a config folder
```

### Meteor Version

0.4.6-0.4.7

### Minecraft Version

1.17.1-1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Do you use some Meteor addons?

**Comment by ColGroLoOl** [comment]
> Do you use some Meteor addons?

Nope

**Comment by seasnail8169** [comment]
specifically which version(s) does this affect
