### ISSUE TITLE
[Bug] Meteor Client dev ver.1392 to 1388: "HUD" editing is incompatible with Vector Addon 0.2.6

### ISSUE THREAD

**Issue by Theboiboi8** [MeteorDevelopment/meteor-client#1901]
### Describe the bug

When Clicking on the edit button in the HUD settings in the meteor GUI the game crashes due to a  "java.lang.NoSuchFieldError: useTeamColor". This worked just fine on ver. ≤1387. 
Detailed Crash log is as follows (deobfuscated using "Not Enough Crashes"):
```
java.lang.NoSuchFieldError: useTeamColor
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.handler$bib000$onGetPlayerColor(PlayerUtils.java:535)
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.getPlayerColor(PlayerUtils.java)
	at meteordevelopment.meteorclient.systems.hud.modules.CombatHud.lambda$render$0(CombatHud.java:215)
	at meteordevelopment.meteorclient.systems.hud.HudRenderer.end(HudRenderer.java:28)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:161)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.client.gui.hud.InGameHud.handler$bah000$onRender(InGameHud:2541)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:416)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:856)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Steps to reproduce

```bash
install Meteor ver. 1388 or higher
install Vector addon ver. 0.2.6
open the meteor gui using rshift
go to HUD in the nav bar at the top of the screen
Click on "Edit"
look at crash
```

### Meteor Version

0.4.7.1388 - 0.4.7.1392

### Minecraft Version

1.18.1 (same on 1.18)

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Awful issue
