### ISSUE TITLE
[Bug] game crash

### ISSUE THREAD

**Issue by Sk-Reaper** [MeteorDevelopment/meteor-client#1931]
### Describe the bug

game crash when i enable hud
crash report 
[2022-01-12-5.log.gz](https://github.com/MeteorDevelopment/meteor-client/files/7859190/2022-01-12-5.log.gz)

### Steps to reproduce

```bash
enable hud and go into game
```

### Meteor Version

meteor client v0.4.7 build #1398

### Minecraft Version

minecraft 1.18.1 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Sk-Reaper** [comment]
Time elapsed: 48882 ms
[07:21:21] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 10270ms or 205 ticks behind
[07:21:51] [Server thread/INFO]: Changing view distance to 4, from 10
[07:21:54] [Server thread/INFO]: Changing simulation distance to 12, from 0
[07:21:62] [Server thread/INFO]: Sk_Reaper[local:E:e28442a6] logged in with entity id 63 at (-90.67942952253011, 1.0, -135.19940545394516)
[07:21:84] [Server thread/INFO]: Sk_Reaper joined the game
[07:21:77] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\INTERWEB\AppData\Roaming\.minecraft\saves\hack test\.\baritone\minecraft\overworld_384
[07:21:78] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\INTERWEB\AppData\Roaming\.minecraft\saves\hack test\.\baritone\minecraft\overworld_384\cache
[07:21:78] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\INTERWEB\AppData\Roaming\.minecraft\saves\hack test\.\baritone\minecraft\overworld_384\waypoints
[07:21:31] [Render thread/INFO]: Loaded 72 advancements
[07:21:50] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\INTERWEB\AppData\Roaming\.minecraft\saves\hack test\.\baritone\minecraft\overworld_384\cache
[07:21:40] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:40] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:51] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:51] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:51] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:51] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'
[07:21:87] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 1359ms
[07:21:08] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'int meteordevelopment.meteorclient.utils.player.FindItemResult.getCount()'
	at anticope.rejects.gui.hud.AppleHud.render(AppleHud.java:44)
	at meteordevelopment.meteorclient.systems.hud.HUD.render(HUD.java:166)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:156)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_329.handler$zdk000$onRender(class_329.java:1541)
	at net.minecraft.class_329.method_1753(class_329.java:416)
	at net.minecraft.class_757.method_3192(class_757.java:856)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

[07:21:76] [Server thread/INFO]: Stopping server
[07:21:76] [Server thread/INFO]: Saving players
[07:21:83] [Server thread/INFO]: Saving worlds
[07:21:83] [Server thread/INFO]: Saving chunks for level 'ServerLevel[hack test]'/minecraft:overworld
[07:21:28] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,-1 from disk C:\Users\INTERWEB\AppData\Roaming\.minecraft\saves\hack test\.\baritone\minecraft\overworld_384\cache
[07:21:31] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 33ms
[07:21:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[hack test]'/minecraft:the_nether
[07:21:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[hack test]'/minecraft:the_end
[07:21:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (hack test): All chunks are saved
[07:21:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[07:21:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[07:21:16] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[07:21:33] [Render thread/INFO]: Saving
[07:21:72] [Render thread/INFO]: Saved in 397 milliseconds.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/13/22, 7:21 AM
Description: Unexpected error

java.lang.NoSuchMethodError: 'int meteordevelopment.meteorclient.utils.player.FindItemResult.getCount()'
	at anticope.rejects.gui.hud.AppleHud.render(AppleHud.java:44)
	at meteordevelopment.meteorclient.systems.hud.HUD.render(HUD.java:166)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:156)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_329.handler$zdk000$onRender(class_329.java:1541)
	at net.minecraft.class_329.method_1753(class_329.java:416)
	at net.minecraft.class_757.method_3192(class_757.java:856)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at anticope.rejects.gui.hud.AppleHud.render(AppleHud.java:44)
	at meteordevelopment.meteorclient.systems.hud.HUD.render(HUD.java:166)
	at meteordevelopment.meteorclient.systems.hud.HUD.onRender(HUD.java:156)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_329.handler$zdk000$onRender(class_329.java:1541)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 1 total; [class_746['Sk_Reaper'/63, l='ClientLevel', x=-90.68, y=1.00, z=-135.20]]
	Chunk stats: 225, 109
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,4,-176), Section: (at 0,4,0 in 2,0,-11; chunk contains blocks 32,-64,-176 to 47,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 74358 game time, 74358 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1388237552 bytes (1323 MiB) / 3154116608 bytes (3008 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.5063
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 10542.93
	Virtual memory used (MB): 9367.90
	Swap memory total (MB): 6526.27
	Swap memory used (MB): 1750.48
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx2992M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: Fabric 1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 5500 GL version 3.2.0 - Build 20.19.15.5063, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 6
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sk_Reaper'/63, l='ServerLevel[hack test]', x=-90.68, y=1.00, z=-135.20]]
	Data Packs: vanilla (incompatible)

-- Meteor Client --
Version: 0.4.7
Dev Build: 1398

[Combat]:
Auto Totem (auto-totem)
Bow Aimbot (bow-aimbot)
Offhand (offhand)

[Player]:
Anti Hunger (anti-hunger)
Auto Respawn (auto-respawn)
Middle Click Extra (middle-click-extra)
Potion Saver (potion-saver)

[Movement]:
No Fall (no-fall)

[Render]:
Better Tooltips (better-tooltips)
Blur (blur)
Camera Tweaks (camera-tweaks)
Esp (esp)
Fullbright (fullbright)
Item Physics (item-physics)
Logout Spots (logout-spots)

[World]:
Auto Mount (auto-mount)

[Misc]:
Better Chat (better-chat)
Message Aura (message-aura)
Vanilla Spoof (vanilla-spoof)

[Rejects]:
Anti Vanish (anti-vanish)
Auto Ez (auto-ez)
Coord Logger (coord-logger)
Rendering (Rendering)
Skeleton Esp (skeleton-esp)

#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\INTERWEB\AppData\Roaming\.minecraft\crash-reports\crash-2022-01-13_07.21.42-client.txt
[07:21:66] [Thread-6/INFO]: Saving
AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (1113 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\INTERWEB\AppData\Roaming\.minecraft\crash-reports\crash-2022-01-13_07.21.42-client.txt
[Crash] Found crash report file: C:\Users\INTERWEB\AppData\Roaming\.minecraft\crash-reports\crash-2022-01-13_07.21.42-client.txt
flush now
flush now

**Comment by ItzVaio** [comment]
this is a damn server code above the other code. meteor client is only CLIENT-sided

**Comment by arlomcwalter** [comment]
its not, hes just running an integrated server (singleplayer world) so all of the logs are combined. this issue is a result of meteor rejects addon, not meteor
