### ISSUE TITLE
Highway Builder Crash [Bug] 

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#2004]
### Describe the bug

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/30/22, 10:14 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index 10 out of bounds for length 10
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at meteordevelopment.meteorclient.systems.modules.misc.BetterChat.onMessageReceive(BetterChat.java:255)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61)
	at net.minecraft.class_338.handler$zom000$onAddMessage(class_338.java:1058)
	at net.minecraft.class_338.method_1804(class_338.java)
	at net.minecraft.class_338.add(class_338.java)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:121)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:108)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:102)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.error(ChatUtils.java:81)
	at meteordevelopment.meteorclient.systems.modules.Module.error(Module.java:110)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder.error(HighwayBuilder.java:278)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder$State.findBlocksToPlace(HighwayBuilder.java:904)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder$State$8.tick(HighwayBuilder.java:516)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder.onTick(HighwayBuilder.java:302)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$bbg000$onPreTick(class_310.java:8535)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at meteordevelopment.meteorclient.systems.modules.misc.BetterChat.onMessageReceive(BetterChat.java:255)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61)
	at net.minecraft.class_338.handler$zom000$onAddMessage(class_338.java:1058)
	at net.minecraft.class_338.method_1804(class_338.java)
	at net.minecraft.class_338.add(class_338.java)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:121)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:108)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:102)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.error(ChatUtils.java:81)
	at meteordevelopment.meteorclient.systems.modules.Module.error(Module.java:110)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder.error(HighwayBuilder.java:278)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder$State.findBlocksToPlace(HighwayBuilder.java:904)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder$State$8.tick(HighwayBuilder.java:516)
	at meteordevelopment.meteorclient.systems.modules.world.HighwayBuilder.onTick(HighwayBuilder.java:302)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$bbg000$onPreTick(class_310.java:8535)

-- Affected level --
Details:
	All players: 1 total; [class_746['Couriersix11'/25, l='ClientLevel', x=-802.18, y=78.00, z=-644.55]]
	Chunk stats: 256, 90
	Level dimension: minecraft:overworld
	Level spawn location: World: (-768,74,-336), Section: (at 0,10,0 in -48,4,-21; chunk contains blocks -768,-64,-336 to -753,319,-321), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 133422 game time, 222808 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, CCRP, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2100666016 bytes (2003 MiB) / 3154116608 bytes (3008 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4531
	Graphics card #1 name: AMD Radeon R7 M260
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x6900
	Graphics card #1 versionInfo: DriverVersion=27.20.21003.1028
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 12202.46
	Virtual memory used (MB): 8960.07
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 1081.67
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx2986M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.18-SNAPSHOT
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.4.8-1417
		minecraft: Minecraft 1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		shulker-dupe: Shulker Dupe 1.0.0
		sodium: Sodium 0.4.0-alpha6+build.14
		worldedit: WorldEdit 7.2.8+6008-1246d61
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 5500 GL version 3.2.0 - Build 20.19.15.4531, Intel
	Window size: 1366x745
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 34629
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/CCRP, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Couriersix11'/25, l='ServerLevel[New World]', x=-802.18, y=78.00, z=-644.55]]
	Data Packs: vanilla, Fabric Mods

-- Meteor Client --
Version: 0.4.8
Dev Build: 1417

[Combat]:
auto-exp
auto-totem
auto-weapon

[Player]:
anti-hunger
auto-respawn
ghost-hand
no-break-delay
no-mining-trace
portals
potion-spoof
reach

[Movement]:
anti-void
boat-fly
no-fall
no-slow

[Render]:
better-tooltips
entity-owner
fullbright
item-physics
logout-spots
no-render
tracers
trajectories
unfocused-cpu
waypoints

[World]:
anti-cactus
auto-breed
enderman-look
highway-builder
mount-bypass

[Misc]:
anti-packet-kick
auto-reconnect
better-chat
inventory-tweaks
middle-click-friend
notifier
vanilla-spoof

### Steps to reproduce

```bash
Minecraft instantly crashed after changing a block or out of block while using highway builder.
```

### Meteor Version

0.4.8 Dev Build Version - 1417

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by SIMULATAN** [comment]
That does not look like a highway builder crash

**Comment by Justgamer101** [comment]
> That does not look like a highway builder crash

highway builder sent a client sided message, so technically it was
