### ISSUE TITLE
[Bug] KillAura with baritone crashes game

### ISSUE THREAD

**Issue by DarkReaper231** [MeteorDevelopment/meteor-client#2043]
### Describe the bug

When you have !follow players + KillAura, it crashes the game once it hits any player

```
[20:50:58] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2382.method_10263()" because "this$0.origin" is null
	at baritone.process.BuilderProcess$BuilderCalculationContext.<init>(BuilderProcess.java:1276) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:688) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:200) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:89) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:59) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:59) ~[baritone-1.18-ff7298be6d479590.jar:?]
	at net.minecraft.class_310.handler$zbf000$runTick(class_310.java:5036) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1720) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
```

### Steps to reproduce

```bash
Run #follow players and enable killaura
```

### Meteor Version

built from latest source using gradle

### Minecraft Version

1.18.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by DarkReaper231** [comment]
Here is crash report ```---- Minecraft Crash Report ----
// You're mean.

Time: 09.02.22 20:50
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2382.method_10263()" because "this$0.origin" is null
	at baritone.process.BuilderProcess$BuilderCalculationContext.<init>(BuilderProcess.java:1276)
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:688)
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:200)
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:89)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:59)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:59)
	at net.minecraft.class_310.handler$zbf000$runTick(class_310.java:5036)
	at net.minecraft.class_310.method_1574(class_310.java:1720)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.process.BuilderProcess$BuilderCalculationContext.<init>(BuilderProcess.java:1276)
	at baritone.process.BuilderProcess.onTick(BuilderProcess.java:688)
	at baritone.utils.PathingControlManager.executeProcesses(PathingControlManager.java:200)
	at baritone.utils.PathingControlManager.preTick(PathingControlManager.java:89)
	at baritone.behavior.PathingBehavior.onTick(PathingBehavior.java:98)
	at baritone.event.GameEventHandler.lambda$onTick$0(GameEventHandler.java:59)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(GameEventHandler.java:59)
	at net.minecraft.class_310.handler$zbf000$runTick(class_310.java:5036)

-- Affected level --
Details:
	All players: 2 total; [class_746['BobBot'/1349, l='ClientLevel', x=-3.56, y=63.88, z=-206.88], class_745['FridgisLOL'/181, l='ClientLevel', x=-2.49, y=63.28, z=-211.98]]
	Chunk stats: 1024, 467
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,68,-224), Section: (at 0,4,0 in 1,4,-14; chunk contains blocks 16,-64,-224 to 31,319,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 7609 game time, 7609 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.11.0-41-generic
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 637993232 bytes (608 MiB) / 1979711488 bytes (1888 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2,90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: GP106 [GeForce GTX 1060 6GB]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288,00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12957,42
	Virtual memory used (MB): 6801,52
	Swap memory total (MB): 9011,20
	Swap memory used (MB): 510,38
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 470.103.01, NVIDIA Corporation
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

-- Meteor Client --
Version: 0.4.8

[Combat]:
aim-assist
auto-armor
auto-totem
auto-weapon
criticals
kill-aura

[Player]:
auto-gap
auto-respawn
fake-player

[Movement]:
no-fall```

**Comment by DarkReaper231** [comment]
Tried with different client, it does not happen so it is meteor only

**Comment by Justgamer101** [comment]
altoclef issue. never happened to me, and the second checkmark is invalid
