### ISSUE TITLE
[Bug] Minecraft crash on 1.18.2

### ISSUE THREAD

**Issue by bram-pkg** [MeteorDevelopment/meteor-client#2105]
### Describe the bug

Minecraft crashes.

```
[11:20:04] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @42a15bdc wants to load interface org.slf4j.Logger. A different interface with the same name was previously loaded by 'app'. (org.slf4j.Logger is in unnamed module of loader 'app')
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.LinkageError: loader constraint violation: loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @42a15bdc wants to load interface org.slf4j.Logger. A different interface with the same name was previously loaded by 'app'. (org.slf4j.Logger is in unnamed module of loader 'app')
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:86) ~[meteor-client-0.4.8-1436.jar:?]
	at net.minecraft.class_2370.<clinit>(class_2370.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:130) ~[client-intermediary.jar:?]
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:61) ~[meteor-client-0.4.8-1436.jar:?]
	at net.minecraft.class_128.handler$zkb000$onAddStackTrace(class_128.java:524) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_555(class_128.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 10 more
```

### Steps to reproduce

```bash
Run fresh 1.18.2 client with latest dev build
```

### Meteor Version

0.4.8-1436

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
1.18.2 dev build is broken and it automatically injects a virus to your pc

**Comment by bram-pkg** [comment]
Good luck having a virus when no code manages to even get executed. Stop trolling.

**Comment by SIMULATAN** [comment]
1.18.2 only works in the dev env, you gotta wait a bit for it to get fixed

**Comment by Justgamer101** [comment]
wow, not a duplicate at all and totally isn't an open one either 4 issues below this one!
#2100

**Comment by bram-pkg** [comment]
This was for a different issue.

**Comment by MineGame159** [comment]
Fixed.
