### ISSUE TITLE
[Bug] StorageESP throws ConcurrentModificationException

### ISSUE THREAD

**Issue by Errorcrafter** [MeteorDevelopment/meteor-client#2151]
### Describe the bug

Joining a server, enabling StorageESP and opening a chest causes the game to eventually crash. Rejoining that server also crashes the game.

Traceback:
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$ValueIterator.next(Unknown Source) ~[?:?]
	at meteordevelopment.meteorclient.utils.world.BlockEntityIterator.next(BlockEntityIterator.java:51) ~[meteor-client-0.4.8-1446.jar:?]
	at meteordevelopment.meteorclient.utils.world.BlockEntityIterator.next(BlockEntityIterator.java:16) ~[meteor-client-0.4.8-1446.jar:?]
	at meteordevelopment.meteorclient.systems.modules.render.StorageESP.onRender(StorageESP.java:174) ~[meteor-client-0.4.8-1446.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.4.8-1446.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47) ~[meteor-client-0.4.8-1446.jar:?]
	at net.minecraft.class_757.handler$bbi000$onRenderWorld(class_757.java:2061) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

### Steps to reproduce

```bash
1) Join a server.
2) Enable StorageESP
3) Open a chest
4) Crash.
```

### Meteor Version

0.4.8 dev build 1446

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
skill issue or config issue

**Comment by Errorcrafter** [comment]
> skill issue or config issue

L + no repos
