### ISSUE TITLE
[Bug] crashes multiple times

### ISSUE THREAD

**Issue by tympanicblock61** [MeteorDevelopment/meteor-client#2198]
### Describe the bug

Encountered an unexpected exception
java.lang.NullPointerException: Cannot read field "field_9236" because "meteordevelopment.meteorclient.MeteorClient.mc.field_1687" is null
	at net.minecraft.class_1657.handler$bgj001$onDropItem(class_1657.java:3835)
	at net.minecraft.class_1657.method_7329(class_1657.java)
	at net.minecraft.class_3222.method_7329(class_3222.java:1568)
	at net.minecraft.class_1657.method_7328(class_1657.java:713)
	at net.minecraft.class_1703.method_7607(class_1703.java:569)
	at net.minecraft.class_1723.method_7595(class_1723.java:151)
	at net.minecraft.class_1657.method_5650(class_1657.java:1402)
	at net.minecraft.class_3218.method_18770(class_3218.java:873)
	at net.minecraft.class_3324.method_14611(class_3324.java:388)
	at net.minecraft.class_3244.method_10839(class_3244.java:1166)
	at net.minecraft.class_2535.method_10768(class_2535.java:424)
	at net.minecraft.class_3242.method_14357(class_3242.java:196)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce

```bash
use meteor client 1459 and idk
```

### Meteor Version

1459

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
send screenshot of ur mods folder or no help

**Comment by MineGame159** [comment]
Fixed in 185db143006b49fa240f120d2af197d9b41fb4cf.
