### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HUNAttila32** [MeteorDevelopment/meteor-client#2214]
### Describe the bug

The client crashes when i run it. I have the addons: python-addon, e621, rejects, orion, reaper and tanuki.

### Steps to reproduce

```bash
Just running the game.
```

### Meteor Version

0.4.9-1464 (beta)

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Most probably the addons are pointing to either 0.4.7 or 0.4.8;
Also send the crash log from `.minecraft/logs/latest.log`.
Inside a codeblock would be better (use triple backticks ` before and after the code).

**Comment by HUNAttila32** [comment]
```[17:18:07] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[17:18:09] [main/WARN]: Mod resolution failed
[17:18:09] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED e621-hud 0.1 {depends minecraft @ [>=1.18.2]}, ROOT_FORCELOAD_SINGLE e621-hud 0.1]
[17:18:09] [main/INFO]: Reason: [HARD_DEP e621-hud 0.1 {depends minecraft @ [>=1.18.2]}, HARD_DEP meteor-client 0.4.9-1464 {depends minecraft @ [>=1.18.2]}, HARD_DEP meteor-rejects 0.2 {depends minecraft @ [>=1.18.2]}, HARD_DEP orion 0.1 {depends minecraft @ [>=1.18.2]}, HARD_DEP python-addon 1.0 {depends minecraft @ [>=1.18.2]}, HARD_DEP tanuki 0.1 {depends minecraft @ [>=1.18.2]}]
[17:18:09] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.18.1] -> add:minecraft 1.18.2 ([[1.18.2,1.19-)])]
[17:18:09] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18.1 with any version between 1.18.2 (inclusive) and 1.19- (exclusive).
Unmet dependency listing:
	 - Mod 'E621 hud' (e621-hud) 0.1 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	 - Mod 'Meteor Client' (meteor-client) 0.4.9-1464 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	 - Mod 'Meteor Rejects' (meteor-rejects) 0.2 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	 - Mod 'Orion' (orion) 0.1 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	 - Mod 'Meteor Python' (python-addon) 1.0 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	 - Mod 'Tanuki' (tanuki) 0.1 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]```

**Comment by C10udburst** [comment]
you need 1.18.2 version of meteor

**Comment by HUNAttila32** [comment]
I have.

**Comment by Lovecrafts-Cat** [comment]
You are on 1.18.2 Meteor, but using 1.18.1 Minecraft.
Make a 1.18.2 instance of MC.

**Comment by HUNAttila32** [comment]
Wdym using 1.18.1 minecraft?

**Comment by Lovecrafts-Cat** [comment]
> Wdym using 1.18.1 minecraft?

```
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18.1 with any version between 1.18.2 (inclusive) and 1.19- (exclusive).
```
Did you even read the error?

**Comment by HUNAttila32** [comment]
I used 1.18.1, 1.18.2 fabric.

**Comment by Lovecrafts-Cat** [comment]
You can't run 1.18.2 Fabric on 1.18.1 Minecraft.
The version numbers are there for a reason.
Please make a 1.18.2 Minecraft instance.

**Comment by HUNAttila32** [comment]
I ran a 1.18.2 Minecraft instance right now and it still is crashes.

**Comment by Lovecrafts-Cat** [comment]
Send the new crash log, I hope what you are saying is true...

**Comment by HUNAttila32** [comment]
[17:47:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:47:24] [Render thread/INFO]: Setting user: observer_chan
[17:47:25] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity = 
java.lang.NumberFormatException: empty String
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at dyv$2.a(SourceFile:429) [1.18.2.jar:?]
	at dyv.a(SourceFile:304) [1.18.2.jar:?]
	at dyv.a(SourceFile:387) [1.18.2.jar:?]
	at dyv.<init>(SourceFile:236) [1.18.2.jar:?]
	at dyr.<init>(SourceFile:454) [1.18.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:197) [1.18.2.jar:?]
[17:47:25] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:47:33] [Render thread/WARN]: Removed resource pack ?dDream?5in from options because it doesn't seem to exist anymore
[17:47:35] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:47:36] [Render thread/INFO]: Reloading ResourceManager: Default
[17:47:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Hangszórók (High Definition Audio Device)
[17:47:49] [Render thread/INFO]: Sound engine started
[17:47:50] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[17:47:50] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[17:47:50] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[17:47:50] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[17:47:50] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[17:47:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[17:47:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:47:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:47:55] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:47:55] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:48:00] [Render thread/INFO]: Stopping!

**Comment by Lovecrafts-Cat** [comment]
Smh, the complete log, from `.minecraft/logs/latest.log`, like before

**Comment by HUNAttila32** [comment]
That's what i did.

**Comment by Lovecrafts-Cat** [comment]
Follow the [Fabric installation guide](https://fabricmc.net/wiki/player:tutorials:install_mcl:windows).
Then run Minecraft 1.18.2 once, without mods.
Then run it again with Meteor.

**Comment by HUNAttila32** [comment]
If you can't read, read what addons i installed with meteor.

**Comment by Lovecrafts-Cat** [comment]
I read them, have you considered that if the log said you are on 1.18.1, then maybe that could be the issue?

**Comment by HUNAttila32** [comment]
I was using 1.18.2 fabric-loader and i ran it without the mods + i read everything on the wiki.
