### ISSUE TITLE
[Bug] crash when loading a profile

### ISSUE THREAD

**Issue by BookWyrm114** [MeteorDevelopment/meteor-client#2245]
### Describe the bug

[15:45:41] [Render thread/ERROR]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1011.method_4307()" because "this.field_5200" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at net.minecraft.client.texture.NativeImageBackedTexture.method_22793(NativeImageBackedTexture:21) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem:211) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:198) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window:310) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1147) ~[?:?]
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2209) ~[?:?]
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2178) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:54) ~[notenoughcrashes-4.1.6+1.18.2-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.handler$dco000$beforeCleanUpAfterCrash(MinecraftClient:18533) ~[?:?]
	at net.minecraft.client.MinecraftClient.cleanUpAfterCrash(MinecraftClient) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:763) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[15:45:41] [Render thread/INFO]: Stopping!

### Steps to reproduce

```bash
I tried loading a profile
```

### Meteor Version

dev build 0.4.9 - 1473

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
Send the FULL crash report
