### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by luketeam5** [MeteorDevelopment/meteor-client#2253]
### Describe the bug

Hello, when starting Meteor with only the client mod and FabricAPI the game crashes with error code `-1` and the following error:

```
java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.isActive(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null
	at net.minecraft.class_310.handler$zme000$onGetFramerateLimit(class_310.java:7088)
	at net.minecraft.class_310.method_16009(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1148)
	at net.minecraft.class_310.method_18098(class_310.java:2209)
	at net.minecraft.class_310.method_18096(class_310.java:2178)
	at net.minecraft.class_310.method_18099(class_310.java:2159)
	at net.minecraft.class_412.method_36877(class_412.java:49)
	at net.minecraft.class_310.<init>(class_310.java:635)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	```
	
	Full log on [HasteBin](https://www.toptal.com/developers/hastebin/ubicecutuj.yaml)

### Steps to reproduce

```bash
Launch the game, game crashes that's all.
```

### Meteor Version

Stable 0.4.8 + Dev 0.4.9 - 1475

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
Meteor doesn't need fabric api to run. I'm not saying this caused the crash.

**Comment by Mathrandom7910** [comment]
I just said that the fabric api didnt cause the crash.

**Comment by Goldsucher07** [comment]
Hello, I had until recently the same error, until I once came to the idea to delete the contents in the Meteor folder in .Minecarft --> **_ATTENTION CONFIGS AND OTHER SETTINGS GET LOGICALLY LOST !!!_** since I had until now no configs or such : just deleted, let generated again and ready :D had you already tried that ?

**Comment by Mathrandom7910** [comment]
Deleting everything is a great example of what not to do.

**Comment by luketeam5** [comment]
> Hello, I had until recently the same error, until I once came to the idea to delete the contents in the Meteor folder in .Minecarft --> **_ATTENTION CONFIGS AND OTHER SETTINGS GET LOGICALLY LOST !!!_** since I had until now no configs or such : just deleted, let generated again and ready :D had you already tried that ?

I tried, however it didn't work. Also I don't think it has anything to do with Meteor files as this was my first time running Meteor on this computer.



> Deleting everything is a great example of what not to do. And can you send the full logs?

I already included full logs in the first message.

**Comment by Vazgen005** [comment]
Same problem when i tried connect with this button
https://vazgen.space/s/d64dc3a975.png
