### ISSUE TITLE
[Compilation Bug] meteor-client.accesswidener maybe invalid

### ISSUE THREAD

**Issue by RewardedIvan** [MeteorDevelopment/meteor-client#2290]
### Describe the bug

```log
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod meteor-client
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:487)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:485)
	... 11 more
```
An idea is **src\main\resources\meteor-client.accesswidener** maybe invalid
This only applies to multimc, thus this isn't an issue with "gradlew runClient"
Check out [this issue](https://github.com/FabricMC/fabric-loom/issues/517)

### Steps to reproduce

```bash
Download https://multimc.org
Make an instance for 1.18.2, then install fabric on it
Git clone this repo
Run "gradlew jar"
Go in the build\libs directory and copy the jar
Paste it in the instance's mods folder
```

### Meteor Version

git commit "7eceb213bed2be8c0ca9e3a07e684ddff34e7390"

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)
- [X] This bug wasn't already reported.
(I have checked every bug report on github)

**Comment by Wide-Cat** [comment]
Instead of running gradlew jar, try gradlew build

**Comment by RewardedIvan** [comment]
Thanks this worked. I think i'm kinda dumb for not listining to the readme.md
