### ISSUE TITLE
[Bug] Meteor crashing

### ISSUE THREAD

**Issue by XFire14** [MeteorDevelopment/meteor-client#2341]
### Describe the bug

Every time i try to launch meteor, (With or without addons) it crashes saying this,  An unexpected issue occured and the game crashed. Or it says ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/2/22, 3:37 PM
Description: Loading NBT data

java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedShort(DataInputStream.java:346)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:595)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at net.minecraft.class_2487.method_10552(class_2487.java:484)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:68)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:42)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.modules.Modules.load(Modules.java:98)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:101)
	at net.minecraft.class_310.handler$zeg004$onInit(class_310.java:4000)
	at net.minecraft.class_310.<init>(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.io.DataInputStream.readUnsignedShort(DataInputStream.java:346)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:595)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at net.minecraft.class_2487.method_10552(class_2487.java:484)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:68)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:42)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.modules.Modules.load(Modules.java:98)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:101)
	at net.minecraft.class_310.handler$zeg004$onInit(class_310.java:4000)
	at net.minecraft.class_310.<init>(class_310.java:639)

-- NBT Tag --
Details:
	Tag name: settings
	Tag type: COMPOUND
Stacktrace:
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:42)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.modules.Modules.load(Modules.java:98)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:101)
	at net.minecraft.class_310.handler$zeg004$onInit(class_310.java:4000)
	at net.minecraft.class_310.<init>(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		AMSIExt.dll:McAfee Cloud AV ThirdParty Ext:26.0.144 9c8b9018 smoldering cucumber:McAfee, LLC
		ASM.Plugin.AudioDevProps2.dll::1.0.1.0:Nahimic
		AudioDevProps2.dll::2.6.15.0:A-Volute
		AudioSes.dll:Audio Session:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22000.132:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		HID.DLL:Hid User Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OWExplorer.dll:Overlay:2.2.198.0:Overwolf LTD
		Ole32.dll:Microsoft OLE for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ProductInfo.dll::1.9.8.0:A-Volute
		PropSys.dll:Microsoft Property System:7.0.22000.184 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SAPIWrapper_x64.dll
		SETUPAPI.DLL:Windows Setup API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22000.376 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		d3d11.dll:Direct3D 11 Runtime:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22000.258 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		gpapi.dll:Group Policy Client API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22000.469 (WinBuild.160101.0800):Microsoft Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.22000.168 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna14345626607008827929.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		mfehida.dll:McAfee Driver Communication:SYSCORE.22.2.0.148:McAfee, LLC
		mfemmsa.dll:McAfee Management Service API:SYSCORE.22.2.0.148:McAfee, LLC
		mscms.dll:Microsoft Color Matching System DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		nvapi64.dll:NVIDIA NVAPI Library, Version 462.21 :27.21.14.6221:NVIDIA Corporation
		nvldumdx.dll:NVIDIA Driver Loader, Version 462.21 :27.21.14.6221:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:27.21.14.6221:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.21.0.36:NVIDIA Corporation
		nvwgf2umx.dll:NVIDIA D3D10 Driver, Version 462.21 :27.21.14.6221:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:Power Profile Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sapi.dll:Speech API:5.3.25805.00 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		symamsi.dll:Symantec AMSI provider:15.7.12.17:Broadcom
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22000.282 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		wbemcomn.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.22000.675 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22000.184 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1436613968 bytes (1370 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6221
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1029
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30421.48
	Virtual memory used (MB): 17674.41
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 264.86
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 462.21, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

-- Meteor Client --
Version: 0.4.8
 

Please Help!

### Steps to reproduce

```bash
By launching minecraft
```

### Meteor Version

0.48

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Your IQ actually dipped so low that it triggered Meteor's anti retard softlock feature, you will receive zero support, no thanks for your time

**Comment by XFire14** [comment]
Answer the question idiot

**Comment by RickyTheRacc** [comment]
See my first reply

**Comment by XFire14** [comment]
Yea, just answer it

**Comment by TaxEvasiqn** [comment]
omg meteor version 0.48??

**Comment by XFire14** [comment]
Uh yea?

**Comment by Saucywan** [comment]
Switch to version 0.4.9

**Comment by XFire14** [comment]
@Saucywan I tried.  same thing.

**Comment by arlomcwalter** [comment]
Delete your configs.
