### ISSUE TITLE
[Bug] Meteor crashes on launch

### ISSUE THREAD

**Issue by maxjiang2021** [MeteorDevelopment/meteor-client#2464]
### Describe the bug

Opening Minecraft crashes.
Crash report:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-06-30, 7:41 p.m.
Description: Loading NBT data

java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at net.minecraft.class_2487.method_10552(class_2487.java:484)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:68)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:42)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:99)
	at net.minecraft.class_310.handler$bnb006$onInit(class_310.java:15418)
	at net.minecraft.class_310.<init>(class_310.java:636)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at net.minecraft.class_2487.method_10552(class_2487.java:484)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:68)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2499$1.method_23249(class_2499.java:42)
	at net.minecraft.class_2499$1.method_23262(class_2499.java:25)
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:99)
	at net.minecraft.class_310.handler$bnb006$onInit(class_310.java:15418)
	at net.minecraft.class_310.<init>(class_310.java:636)

-- NBT Tag --
Details:
	Tag name: elements
	Tag type: LIST
Stacktrace:
	at net.minecraft.class_2487.method_10581(class_2487.java:489)
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71)
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57)
	at net.minecraft.class_2507.method_10626(class_2507.java:147)
	at net.minecraft.class_2507.method_10625(class_2507.java:91)
	at net.minecraft.class_2507.method_10633(class_2507.java:82)
	at meteordevelopment.meteorclient.systems.System.load(System.java:64)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:88)
	at meteordevelopment.meteorclient.systems.Systems.load(Systems.java:94)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:99)
	at net.minecraft.class_310.handler$bnb006$onInit(class_310.java:15418)
	at net.minecraft.class_310.<init>(class_310.java:636)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22000.132:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2205.7 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PROPSYS.dll:Microsoft Property System:7.0.22000.184 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Setup API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.593 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		atiadlxx.dll:ADL:7.21.30.1444:Advanced Micro Devices, Inc.
		atig6pxx.dll:atiglpxx.dll:8.14.01.6564:Advanced Micro Devices, Inc. 
		atig6txx.dll:atigktxx.dll:8.14.01.6564:Advanced Micro Devices, Inc. 
		atio6axx.dll:AMD OpenGL driver:8.14.11000.14761:Advanced Micro Devices, Inc.
		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dxva2.dll:DirectX Video Acceleration 2.0 DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22000.258 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.22000.168 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna11305744577354090758.dll
		jna3796985177753269133.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		mscms.dll:Microsoft Color Matching System DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:Power Profile Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sapi.dll:Speech API:5.3.25805.00 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22000.282 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		wbemcomn.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.22000.739 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22000.184 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1252424912 bytes (1194 MiB) / 1711276032 bytes (1632 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 PRO 5650U with Radeon Graphics     
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=30.0.13040.4003
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Virtual memory max (MB): 21838.43
	Virtual memory used (MB): 14094.48
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 261.27
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		citresewn: CIT Resewn 1.1.0+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.0+1.19
		continuity: Continuity 2.0.0+1.19
		custom-crosshair-mod: Custom Crosshair Mod 1.4.0-fabric
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fabric: Fabric API 0.55.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		indium: Indium 1.0.5+mc1.19
		invmove: InvMove 0.8.0
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		jsmacros: Js Macros 1.7.0
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
			io_noties_prism4j: prism4j 2.0.0
			org_graalvm_js_js: js 22.1.0
			org_graalvm_regex_regex: regex 22.1.0
			org_graalvm_sdk_graal-sdk: graal-sdk 22.1.0
			org_graalvm_truffle_truffle-api: truffle-api 22.1.0
			org_javassist_javassist: javassist 3.28.0-GA
		lithium: Lithium 0.8.0
		malilib: MaLiLib 0.12.1
		meteor-client: Meteor Client 0.5.0-1512
			baritone: Baritone 1.19-SNAPSHOT
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 4.0.0
		multiconnect: MultiConnect 1.6-beta.16
			multiconnect-api: MultiConnect API 1.6-beta.16
		phosphor: Phosphor 0.8.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		status-effect-bars: Status Effect Bars 1.0.1
		suggestion_tweaker: Suggestion Tweaker 1.19-1.2.1
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
		toolscroll: Tooltip Scroll 1.0.2
		tweakeroo: Tweakeroo 0.13.3
		viafabric: ViaFabric 0.4.7+5-main
			org_yaml_snakeyaml: snakeyaml 1.30
			viafabric-mc119: ViaFabric for 1.19 0.4.7+5-main
			viaversion: ViaVersion 4.3.0
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.23.2
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.40.04 30.0.13040.4003, ATI Technologies Inc.
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 PRO 5650U with Radeon Graphics 

-- Meteor Client --
Version: 0.5.0
Dev Build: 1512
```
This used to work, but now it doesn't (I didn't do anything)

### Steps to reproduce

```bash
Open Minecraft.
```

### Meteor Version

0.5.0-1512

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by maxjiang2021** [comment]
I just realized that one of the configuration files are corrupted.
