### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CrazyWillBear** [MeteorDevelopment/meteor-client#2474]
### Describe the bug

Every time I move between servers in a BungeeCord proxy, my client crashes with error code -1.

### Steps to reproduce

```bash
I join capbearmc.ddns.net, I join the survival server, and I freshly configure Meteor Client. Then, any subsequent times I try and rejoin the server and then join the survival server, it crashes.
```

### Meteor Version

meteor-client-0.5.0-1518

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CrazyWillBear** [comment]
log:
```
[13:52:59] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[13:52:59] [main/INFO]: Loading 5 mods:
	- baritone 1.19-SNAPSHOT via meteor-client
	- fabricloader 0.14.8
	- java 17
	- meteor-client 0.5.0-1512
	- minecraft 1.19
[13:52:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/crazy/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[13:52:59] [main/INFO]: Compatibility level set to JAVA_17
[13:53:00] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[13:53:00] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[13:53:02] [main/INFO]: Building optimized datafixer
[13:53:08] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:53:09] [Render thread/INFO]: Setting user: crazywillbear
[13:53:10] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[13:53:18] [Render thread/INFO]: Narrator library for x64 successfully loaded
[13:53:18] [Render thread/INFO]: Reloading ResourceManager: Default
[13:53:19] [Render thread/INFO]: Initializing Meteor Client
[13:53:21] [Render thread/INFO]: Reflections took 2233 ms to scan 1 urls, producing 16 keys and 763 values
[13:53:22] [Render thread/WARN]: Failed to load font: FontInfo[family=Amiri, type=Regular]
[13:53:22] [Render thread/WARN]: Failed to load font: FontInfo[family=Amiri, type=Regular]
[13:53:22] [Render thread/WARN]: Failed to load font: FontInfo[family=Caladea, type=Italic]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans, type=Regular]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans, type=Regular]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans Condensed, type=Regular]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans Condensed, type=Regular]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans Mono, type=Regular]
[13:53:23] [Render thread/WARN]: Failed to load font: FontInfo[family=DejaVu Sans Mono, type=Regular]
[13:53:24] [Render thread/WARN]: Failed to load font: FontInfo[family=Frank Ruehl CLM, type=Regular]
[13:53:24] [Render thread/WARN]: Failed to load font: FontInfo[family=Frank Ruehl CLM, type=Regular]
[13:53:24] [Render thread/WARN]: Failed to load font: FontInfo[family=HP Simplified, type=Bold]
[13:53:25] [Render thread/WARN]: Failed to load font: FontInfo[family=Linux Libertine G, type=Regular]
[13:53:25] [Render thread/WARN]: Failed to load font: FontInfo[family=Linux Libertine G, type=Regular]
[13:53:26] [Render thread/WARN]: Failed to load font: FontInfo[family=Miriam Mono CLM, type=Regular]
[13:53:26] [Render thread/WARN]: Failed to load font: FontInfo[family=Miriam Mono CLM, type=Regular]
[13:53:27] [Render thread/WARN]: Failed to load font: FontInfo[family=Rubik, type=Regular]
[13:53:27] [Worker-Bootstrap-9/INFO]: 4256 Datafixer optimizations took 24903 milliseconds
[13:53:28] [Render thread/INFO]: Found 148 font families.
[13:53:29] [Render thread/INFO]: Loading
[13:53:29] [Render thread/INFO]: Loaded in 60 milliseconds
[13:53:29] [Render thread/INFO]: Reflections took 88 ms to scan 1 urls, producing 16 keys and 763 values
[13:53:29] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:53:29] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:53:29] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Razer Kraken V3 X)
[13:53:29] [Render thread/INFO]: Sound engine started
[13:53:29] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[13:53:29] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[13:53:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:53:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:53:29] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:53:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:53:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:53:30] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:53:30] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[13:53:30] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:53:30] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:53:32] [Render thread/INFO]: Checking latest version of Meteor Client
[13:53:34] [Render thread/INFO]: Connecting to mc.capbear.net, 25565
[13:53:35] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[13:53:35] [Render thread/WARN]: Method overwrite conflict for getChunks in meteor-client.mixins.json:ClientChunkMapAccessor from mod meteor-client, previously written by baritone.launch.mixins.MixinChunkArray. Skipping method.
[13:53:35] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256
[13:53:35] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:35] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\waypoints
[13:53:35] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[13:53:35] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: minecraft:mangrove_propagule has a collision shape and an offset type, but is not marked as dynamicShape in its properties.
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:708) ~[client-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_2246.method_26979(class_2246.java:1078) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11126(class_634.java:1401) ~[client-intermediary.jar:?]
	at net.minecraft.class_2790.method_12001(class_2790.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_2790.method_11054(class_2790.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[13:53:35] [Render thread/INFO]: [CHAT]   Select a server to join by clicking on it in chat!
[13:53:35] [Render thread/INFO]: [CHAT]   §3- §oSurvival
[13:53:35] [Render thread/INFO]: [CHAT]   §3- §oCreative
[13:53:35] [Render thread/INFO]: Loaded 15 advancements
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,0 from disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 34ms
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,0 from disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 25ms
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loading region 0,-1 from disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 26ms
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loading region -1,-1 from disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:35] [pool-3-thread-1/INFO]: [STDOUT]: Loaded region successfully in 18ms
[13:53:38] [pool-3-thread-3/INFO]: [STDOUT]: Started saving the world in a new thread
[13:53:38] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\overworld_384
[13:53:38] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\overworld_384\cache
[13:53:38] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\overworld_384\waypoints
[13:53:38] [pool-3-thread-3/INFO]: [STDOUT]: Saving region -1,0 to disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:38] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saving region 0,-1 to disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:38] [ForkJoinPool.commonPool-worker-2/INFO]: [STDOUT]: Saving region 0,0 to disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:38] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region -1,-1 to disk C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\the_end_256\cache
[13:53:38] [Render thread/INFO]: Saving
[13:53:38] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[13:53:38] [ForkJoinPool.commonPool-worker-2/INFO]: [STDOUT]: Saved region successfully
[13:53:38] [ForkJoinPool.commonPool-worker-1/INFO]: [STDOUT]: Saved region successfully
[13:53:38] [pool-3-thread-3/INFO]: [STDOUT]: Saved region successfully
[13:53:38] [pool-3-thread-3/INFO]: [STDOUT]: World save took 51ms
[13:53:38] [Render thread/INFO]: Saved in 58 milliseconds.
[13:53:39] [pool-3-thread-3/INFO]: [STDOUT]: Started saving the world in a new thread
[13:53:39] [pool-3-thread-3/INFO]: [STDOUT]: World save took 0ms
[13:53:39] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\crazy\AppData\Roaming\.minecraft\baritone\mc.capbear.net\minecraft\overworld_384
[13:53:39] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[13:53:39] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: minecraft:mangrove_propagule has a collision shape and an offset type, but is not marked as dynamicShape in its properties.
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1117) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:708) ~[client-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_2246.method_26979(class_2246.java:1078) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11126(class_634.java:1401) ~[client-intermediary.jar:?]
	at net.minecraft.class_2790.method_12001(class_2790.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_2790.method_11054(class_2790.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[13:53:39] [Render thread/INFO]: [CHAT]   KEEP INVENTORY IS NOW OFF!!! + capbearmc.ddns.net will be inactive on July 31st, please use mc.capbear.net.
[13:53:39] [Render thread/INFO]: [CHAT]   crazywillbear joined the game
[13:53:39] [Render thread/INFO]: Loaded 424 advancements
[13:53:39] [Worker-Main-29/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[13:53:39] [Worker-Main-30/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[13:53:39] [Thread-5/INFO]: Saving
```

friendlist:
```

  
 color a   ÿ  rainbow  r     b   ´ g   ÿ  attack 	  friends      
```

**Comment by CodeDoc537** [comment]
It’s an anarchy client, not made for cheating.
You won’t be getting much help.

**Comment by arlomcwalter** [comment]
nothing related to meteor in the logs
