### ISSUE TITLE
[Bug] Crash on network disconnect

### ISSUE THREAD

**Issue by ItsIsntItsKeera** [MeteorDevelopment/meteor-client#2491]
### Describe the bug

So if u disconnect unintentionally (from either crap wifi or packet thing)  it will crash the game (all mod and addon in picture)
Also there no crash log so there normal log
```
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8320(net.minecraft.class_2338)" because "meteordevelopment.meteorclient.MeteorClient.mc.field_1687" is null
	at meteordevelopment.meteorclient.utils.misc.MeteorStarscript.crosshairValue(MeteorStarscript.java:377)
	at meteordevelopment.starscript.Starscript.run(Starscript.java:68)
	at meteordevelopment.starscript.Starscript.run(Starscript.java:85)
	at meteordevelopment.meteorclient.systems.hud.elements.TextHud.runTick(TextHud.java:184)
	at meteordevelopment.meteorclient.systems.hud.elements.TextHud.tick(TextHud.java:162)
	at meteordevelopment.meteorclient.systems.hud.Hud.onTick(Hud.java:199)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_310.handler$bdi003$onTick(class_310.java:7438)
	at net.minecraft.class_310.method_1574(class_310.java:1869)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
![eadsadsad](https://user-images.githubusercontent.com/91017793/178093676-77fe14fc-dc58-4207-8769-f97bf2a53f13.png)

### Steps to reproduce

```bash
1. get meteor 1526 build
2. trigger disconnect with disconnecting wifi or packet
3. crash without crash log
```

### Meteor Version

0.5.0 1526 dev build

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ItsIsntItsKeera** [comment]
also there liquidbounce in it but it forge 1.8.9 which isnt loaded, so that should not the problem

**Comment by ItsIsntItsKeera** [comment]
it also happen on 1525, not 1524 tho

**Comment by ItsIsntItsKeera** [comment]
nope 1524 also crash

**Comment by white-devil42** [comment]
same here 1527
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 07/07/22, 12:43 pm
Description: mouseReleased event handler

java.lang.NullPointerException: Cannot read field "name" because the return value of "meteordevelopment.meteorclient.utils.network.Http$Request.sendJson(java.lang.reflect.Type)" is null
	at meteordevelopment.meteorclient.systems.friends.Friend.getName(Friend.java:86)
	at meteordevelopment.meteorclient.systems.friends.Friend.refresh(Friend.java:40)
	at meteordevelopment.meteorclient.gui.tabs.builtin.FriendsTab$FriendsScreen.initTable(FriendsTab.java:124)
	at meteordevelopment.meteorclient.gui.tabs.builtin.FriendsTab$FriendsScreen.initWidgets(FriendsTab.java:85)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25426(WidgetScreen.java:99)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at meteordevelopment.meteorclient.gui.tabs.Tab.openScreen(Tab.java:23)
	at anticope.rejects.gui.themes.rounded.widgets.WMeteorTopBar$WTopBarButton.onPressed(WMeteorTopBar.java:74)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:134)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.meteorclient.systems.friends.Friend.getName(Friend.java:86)
	at meteordevelopment.meteorclient.systems.friends.Friend.refresh(Friend.java:40)
	at meteordevelopment.meteorclient.gui.tabs.builtin.FriendsTab$FriendsScreen.initTable(FriendsTab.java:124)
	at meteordevelopment.meteorclient.gui.tabs.builtin.FriendsTab$FriendsScreen.initWidgets(FriendsTab.java:85)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25426(WidgetScreen.java:99)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at meteordevelopment.meteorclient.gui.tabs.Tab.openScreen(Tab.java:23)
	at anticope.rejects.gui.themes.rounded.widgets.WMeteorTopBar$WTopBarButton.onPressed(WMeteorTopBar.java:74)
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:27)
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142)
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:134)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: meteordevelopment.meteorclient.gui.tabs.builtin.GuiTab.GuiScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Affected level --
Details:
	All players: 1 total; [class_746['WhiteDevil'/14, l='ClientLevel', x=515.75, y=4.00, z=80.36]]
	Chunk stats: 961, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,4,160), Section: (at 0,4,0 in 5,0,10; chunk contains blocks 80,-64,160 to 95,319,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2794164 game time, 1000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 361573808 bytes (344 MiB) / 2623537152 bytes (2502 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14057.16
	Virtual memory used (MB): 10234.54
	Swap memory total (MB): 6000.00
	Swap memory used (MB): 431.66
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.19
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
		bedrockminer: Bedrock Miner 1.0.0
		clientcommands: Client Commands 2.7
			clientarguments: clientarguments 1.4.1
		clumps: Clumps 9.0.0+3
		cmdkeybind: Command Macros 1.5.4-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		extremesoundmuffler: Extreme sound muffler 3.27_fabric-1.19
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		inventoryhud: Inventory HUD + 3.4.2
		inventorytotem-fabric: Inventory Totem (Fabric) 1.7
		itemscroller: Item Scroller 0.16.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.0.0.206
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		litematica: Litematica 0.11.3
		litematica_printer: Litematica Printer 2.4
		malilib: MaLiLib 0.12.1
		meteor-client: Meteor Client 0.5.0-1518
			baritone: Baritone 1.19-SNAPSHOT
		meteor-rejects: Meteor Rejects 0.2
			seedcrackerx-api: SeedCrackerX API 2.10.1
		meteor-villager-roller: Meteor Villager Roller 1.3+mc1.19-rev.b16e705
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 4.0.0
		mousetweaks: Mouse Tweaks 2.22
		multiconnect: MultiConnect 1.6-beta.17
			multiconnect-api: MultiConnect API 1.6-beta.17
		replaymod: Replay Mod 1.19-2.6.6
		seedcrackerx: SeedCrackerX 2.13
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 706e4f1b7aa6b42b3627f682a311d06280d80b5c
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		seedmapper: SeedMapper 1.5.5
		smoothboot: Smooth Boot 1.19-1.7.1
		tweakeroo: Tweakeroo 0.13.3
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.9664, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['WhiteDevil'/14, l='ServerLevel[Test World]', x=515.75, y=4.00, z=80.36]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

-- Meteor Client --
Version: 0.5.0
Dev Build: 1518

[Combat]:
auto-armor
criticals
kill-aura

[Player]:
anti-hunger
auto-replenish
auto-tool
middle-click-extra
portals

[Movement]:
air-jump
anti-void
elytra-boost
no-fall
no-slow

[Render]:
better-tooltips
boss-stack
break-indicators
city-esp
entity-owner
esp
fullbright
logout-spots
nametags
no-render
tracers
trajectories
tunnel-ESP
unfocused-cpu

[Misc]:
anti-packet-kick
inventory-tweaks
server-spoof

[Rejects]:
anti-vanish
coord-logger
skeleton-esp
sound-locator

**Comment by BongWaterBilly** [comment]
I'm getting the same crash on the latest dev version. I played around a bit with it and its the hud that's causing the crash for me. If I turn off the hud fully it stops the crash on disconnect and funnily enough it fixes the physics cape mod that I have that gives my cape physics. If i load into a server with hud on it has messed up physics and yea on disconnect with hud it crashes and without hud both things are fixed.

**Comment by ItsIsntItsKeera** [comment]
Alright i guess i gonna disable HUD for now

**Comment by MineGame159** [comment]
Already fixed in latest dev builds
