### ISSUE TITLE
[Bug] Crash on startup, seems to be an issue with the gui rendering

### ISSUE THREAD

**Issue by BookWyrm114** [MeteorDevelopment/meteor-client#2560]
### Describe the bug

the game starts up, and crashes just before loding the title screen, at the end of the startup process

error:

[12:04:28] [Render thread/ERROR]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.gui.GuiTheme.hideHUD()" because the return value of "meteordevelopment.meteorclient.gui.GuiThemes.get()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1) ~[?:?]
	at meteordevelopment.meteorclient.MeteorClient.onOpenScreen(MeteorClient.java:143) ~[meteor-client-0.5.0-1559.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.0-1559.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61) ~[meteor-client-0.5.0-1559.jar:?]
	at net.minecraft.client.MinecraftClient.handler$edk000$onSetScreen(MinecraftClient:52464) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient) ~[?:?]
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2120) ~[?:?]
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2090) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:54) ~[notenoughcrashes-4.1.6+1.19-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.handler$ffh000$beforeCleanUpAfterCrash(MinecraftClient:33951) ~[?:?]
	at net.minecraft.client.MinecraftClient.cleanUpAfterCrash(MinecraftClient) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:754) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[12:04:28] [Render thread/INFO]: Stopping!

### Steps to reproduce

```bash
not sure, the error isn't super clear what conflict is causing this
```

### Meteor Version

dev build 0.5.0 - 1559

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
remove not enough crashes and send the crash report again

**Comment by seasnail8169** [comment]
also send the whole file

**Comment by BookWyrm114** [comment]
sure thing, here it is:
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/9163074/latest.log)

**Comment by nickcat325** [comment]
Config issue or mod incompatibility maybe?

**Comment by saharb123** [comment]
same happened to me, and i don't know what to do! any help will help
