### ISSUE TITLE
[Bug] Crash meteor

### ISSUE THREAD

**Issue by spacewaretwo** [MeteorDevelopment/meteor-client#2586]
### Describe the bug

`java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract java.lang.String getPackage()' of abstract class meteordevelopment.meteorclient.addons.MeteorAddon.
	at meteordevelopment.meteorclient.MeteorClient.lambda$onInitializeClient$3(MeteorClient.java:88)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:88)
	at net.minecraft.class_310.handler$zon004$onInit(class_310.java:9914)
	at net.minecraft.class_310.<init>(class_310.java:636)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

### Steps to reproduce

```bash
Launch meteor
```

### Meteor Version

0.5.0-1568

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
you have an outdated addon

**Comment by spacewaretwo** [comment]
It is impossible to create an addon for a new version, because in the Meteor code they forgot to put abstract somewhere.

**Comment by seasnail8169** [comment]
> It is impossible to create an addon for a new version, because in the Meteor code they forgot to put abstract somewhere.
> 
> 

that's completely wrong, addons just have to implement the abstract method lol.
