### ISSUE TITLE
[Bug] Softlock if commit history loading is failing

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#3007]
### Describe the bug

On the title screen, if you click on the name of the component it opens up a commit history, however it is completely broken and fails to parse JSON and leaves player in soft-locked state with only empty window on a blank screen.

![image](https://user-images.githubusercontent.com/20772987/204717800-cfde2cf8-73a5-4fd4-9b33-a2287e5af2e1.png)

Following is being reported in logs:
```
[08:40:47] [Render thread/INFO]: Checking latest version of Meteor Client
[08:40:47] [pool-5-thread-2/ERROR]: Uncaught exception in thread "pool-5-thread-2"
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:66) ~[gson-2.8.9.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_442.md600a72$lambda$onRenderIdkDude$2$0(class_442.java:1046) ~[client-intermediary.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:61) ~[gson-2.8.9.jar:?]
	... 5 more
[08:40:47] [pool-5-thread-3/ERROR]: Uncaught exception in thread "pool-5-thread-3"
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at meteordevelopment.meteorclient.utils.network.Http$Request.sendJson(Http.java:118) ~[meteor-client-0.5.1-1694.jar:?]
	at meteordevelopment.meteorclient.utils.player.TitleScreenCredits.lambda$init$1(TitleScreenCredits.java:46) ~[meteor-client-0.5.1-1694.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.9.jar:?]
	... 7 more
[08:48:34] [pool-5-thread-4/ERROR]: Uncaught exception in thread "pool-5-thread-4"
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:?]
	at meteordevelopment.meteorclient.utils.network.Http$Request.sendJson(Http.java:118) ~[meteor-client-0.5.1-1694.jar:?]
	at meteordevelopment.meteorclient.gui.screens.CommitsScreen.lambda$new$0(CommitsScreen.java:35) ~[meteor-client-0.5.1-1694.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.9.jar:?]
	... 7 more
```

### Steps to reproduce

```bash
1. Click on purple MeteorClient
```

### Meteor Version

0.5.1-1694

### Minecraft Version

1.19.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by maxsupermanhd** [comment]
No

**Comment by RacoonDog** [comment]
might be like a github api rate limit type thing

**Comment by maxsupermanhd** [comment]
Perhaps add some sort of logging to exceptions or catch them and close the screen. Catching exceptions is always a good thing.

**Comment by Big-Iron-Cheems** [comment]
Solved in #4501
