### ISSUE TITLE
Entity owner seems to fail to parse json

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#3168]
### Describe the bug

Entity owner does not work, showing "Retrieving".

In logs following exception is thrown:
```
[02:24:31] [pool-5-thread-5/ERROR]: Uncaught exception in thread "pool-5-thread-5"
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1124) ~[gson-2.10.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1094) ~[gson-2.10.jar:?]
	at meteordevelopment.meteorclient.utils.network.Http$Request.sendJson(Http.java:118) ~[meteor-client-0.5.2-1741.jar:?]
	at meteordevelopment.meteorclient.systems.modules.render.EntityOwner.lambda$getOwnerName$0(EntityOwner.java:122) ~[meteor-client-0.5.2-1741.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384) ~[gson-2.10.jar:?]
	... 8 more
```

### Steps to reproduce

```bash
Use entity owner
```

### Meteor Version

0.5.2-1741

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
Network issue

**Comment by maxsupermanhd** [comment]
It can not be a network issue.

**Comment by maxsupermanhd** [comment]
Doing this solves issue, it is not a networking problem. Somehow meteor's HTTP client responds with string "Hello world!\n\n".
Patch:
```diff
diff --git a/src/main/java/meteordevelopment/meteorclient/systems/modules/render/EntityOwner.java b/src/main/java/meteordevelopment/meteorclient/systems/modules/render/EntityOwner.java
index be6dabdf..0c8677d0 100644
--- a/src/main/java/meteordevelopment/meteorclient/systems/modules/render/EntityOwner.java
+++ b/src/main/java/meteordevelopment/meteorclient/systems/modules/render/EntityOwner.java
@@ -5,6 +5,8 @@
 
 package meteordevelopment.meteorclient.systems.modules.render;
 
+import com.google.gson.Gson;
+import com.google.gson.JsonSyntaxException;
 import meteordevelopment.meteorclient.events.render.Render2DEvent;
 import meteordevelopment.meteorclient.mixin.ProjectileEntityAccessor;
 import meteordevelopment.meteorclient.renderer.Renderer2D;
@@ -28,10 +30,18 @@ import net.minecraft.entity.player.PlayerEntity;
 import net.minecraft.entity.projectile.ProjectileEntity;
 import org.joml.Vector3d;
 
+import java.io.IOException;
+import java.net.URI;
+import java.net.URISyntaxException;
+import java.net.http.HttpClient;
+import java.net.http.HttpRequest;
+import java.net.http.HttpResponse;
 import java.util.HashMap;
 import java.util.Map;
 import java.util.UUID;
 
+import static java.net.http.HttpRequest.newBuilder;
+
 public class EntityOwner extends Module {
     private static final Color BACKGROUND = new Color(0, 0, 0, 75);
     private static final Color TEXT = new Color(255, 255, 255);
@@ -119,11 +129,30 @@ public class EntityOwner extends Module {
         // Makes a HTTP request to Mojang API
         MeteorExecutor.execute(() -> {
             if (isActive()) {
-                ProfileResponse res = Http.get("https://sessionserver.mojang.com/session/minecraft/profile/" + uuid.toString().replace("-", "")).sendJson(ProfileResponse.class);
-
-                if (isActive()) {
-                    if (res == null) uuidToName.put(uuid, "Failed to get name");
-                    else uuidToName.put(uuid, res.name);
+                String url = "https://sessionserver.mojang.com/session/minecraft/profile/" + uuid.toString().replace("-", "");
+                info(url);
+                HttpRequest req = null;
+                try {
+                    req = HttpRequest.newBuilder().uri(new URI(url)).GET().build();
+                } catch (URISyntaxException e) {
+                    throw new RuntimeException(e);
+                }
+                String resp = null;
+                try {
+                    resp = HttpClient.newHttpClient().send(req, HttpResponse.BodyHandlers.ofString()).body();
+                } catch (IOException | InterruptedException e) {
+                    throw new RuntimeException(e);
+                }
+                info(resp);
+                try {
+                    ProfileResponse res = new Gson().fromJson(resp, ProfileResponse.class);
+                    if (isActive()) {
+                        if (res == null) uuidToName.put(uuid, "Failed to get name");
+                        else uuidToName.put(uuid, res.name);
+                    }
+                } catch (JsonSyntaxException e) {
+                    info(e.toString());
+                    throw e;
                 }
             }
         });
```
