### ISSUE TITLE
[BUG] .enchant crashed when adding/removing single enchantments

### ISSUE THREAD

**Issue by unseeyou** [MeteorDevelopment/meteor-client#3254]
### Describe the bug

version: 0.5.2 on 1.19.3
server: random minehut server
Whenever I try to add or remove a single enchantment with the `.enchant` command, it crashes my game.

### Steps to reproduce

```bash
# steps to reproduce
1. connect to a minehut server you have op on
2. in creative mode, add sharp 100 to a netherite sword with `.enchant one`
3. watch as the game crashes (unless its just me)
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
if you're reporting a crash, you should include the damn crash report

**Comment by unseeyou** [comment]
there is no view crash report button, just exit code -1

**Comment by unseeyou** [comment]
my bad im rlly dumb I found the crash report folder

**Comment by unseeyou** [comment]
```---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-01-31 19:01:05
Description: keyPressed event handler

java.lang.IllegalArgumentException: Argument 'enchantment' is defined as class_6883, not class net.minecraft.class_1887
	at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:92)
	at meteordevelopment.meteorclient.systems.commands.commands.EnchantCommand.one(EnchantCommand.java:92)
	at meteordevelopment.meteorclient.systems.commands.commands.EnchantCommand.lambda$build$1(EnchantCommand.java:41)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:88)
	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:83)
	at net.minecraft.class_634.handler$zlj000$onSendChatMessage(class_634.java:5236)
	at net.minecraft.class_634.method_45729(class_634.java)
	at net.minecraft.class_408.method_44056(class_408.java:253)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:371)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_309.method_1466(class_309.java:367)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:92)
	at meteordevelopment.meteorclient.systems.commands.commands.EnchantCommand.one(EnchantCommand.java:92)
	at meteordevelopment.meteorclient.systems.commands.commands.EnchantCommand.lambda$build$1(EnchantCommand.java:41)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:88)
	at meteordevelopment.meteorclient.systems.commands.Commands.dispatch(Commands.java:83)
	at net.minecraft.class_634.handler$zlj000$onSendChatMessage(class_634.java:5236)
	at net.minecraft.class_634.method_45729(class_634.java)
	at net.minecraft.class_408.method_44056(class_408.java:253)
	at net.minecraft.class_408.method_25404(class_408.java:101)
	at net.minecraft.class_309.method_1454(class_309.java:371)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_309.method_1466(class_309.java:367)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_309.method_1466(class_309.java:367)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['unseeyou'/9, l='ClientLevel', x=-22.50, y=48.00, z=6.47]]
	Chunk stats: 1024, 361
	Level dimension: minecraft:void
	Level spawn location: World: (-25,49,2), Section: (at 7,1,2 in -2,3,0; chunk contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 94686 game time, 178530 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: REDACTED
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 602996264 bytes (575 MiB) / 1912602624 bytes (1824 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Vivi Display Adapter
	Graphics card #0 vendor: Vivi International
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.1.236.96
	Graphics card #1 name: NVIDIA Quadro P500
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d33
	Graphics card #1 versionInfo: DriverVersion=30.0.14.9729
	Graphics card #2 name: Intel(R) UHD Graphics 620
	Graphics card #2 vendor: Intel Corporation (0x8086)
	Graphics card #2 VRAM (MB): 1024.00
	Graphics card #2 deviceId: 0x5917
	Graphics card #2 versionInfo: DriverVersion=31.0.101.2115
	Graphics card #3 name: Duet Display
	Graphics card #3 vendor: Duet, Inc.
	Graphics card #3 VRAM (MB): 0.00
	Graphics card #3 deviceId: unknown
	Graphics card #3 versionInfo: DriverVersion=14.30.43.713
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34639.19
	Virtual memory used (MB): 17569.64
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 43.88
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.70.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.1+f1e4495b85
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.10+99f9db8085
			fabric-command-api-v1: Fabric Command API (v1) 1.2.20+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.16+99f9db8085
			fabric-commands-v0: Fabric Commands (v0) 0.2.37+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.45+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.2+33a4e2d785
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.38+f1e4495b85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.40+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.6+99f9db8085
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.9+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.29+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.27+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.15+99f9db8085
			fabric-networking-v0: Fabric Networking (v0) 0.3.32+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.1+f1e4495b85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.2+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.1+afca2f3e85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.24+99f9db8085
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.1+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.11+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.13+f1e4495b85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.2.0+1d37d50285
		fabricloader: Fabric Loader 0.14.12
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.5.2-1741
			baritone-meteor: Baritone 1.19.3-SNAPSHOT
		meteor-rejects: Meteor Rejects 0.2
			seedcrackerx-api: SeedCrackerX API 2.10.1
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.0.2
		nochatreports: No Chat Reports 1.19.3-v1.19.0
		phosphor: Phosphor 0.8.1
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		sodium: Sodium 0.4.7+build.21
		sodium-extra: Sodium Extra 0.4.16+mc1.19.3-build.91
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		worldedit: WorldEdit 7.2.13+46576cc
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Quadro P500/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

-- Meteor Client --

Version: 0.5.2
Dev Build: 1741

[[ Active Modules ]]

[Combat]:
auto-totem

[Render]:
better-tooltips
fullbright
logout-spots
nametags
tracers
trajectories
unfocused-cpu

[Misc]:
anti-packet-kick
auto-reconnect
inventory-tweaks
server-spoof

[[ Active Hud Elements ]]
armor
lag-notifier
player-model
player-radar
Text
{TPS: #1{round(server.tps, 1)}}
combat
Text
{Ping: #1{ping}}
potion-timers
Text
{FPS: #1{fps}}
```

**Comment by Wide-Cat** [comment]
Update to the latest Dev build, this has already been fixed

**Comment by unseeyou** [comment]
but isnt it 0.5.2?

**Comment by Big-Iron-Cheems** [comment]
You are about 20 dev builds behind the latest one.
Compare your build number with the one on the website.

**Comment by unseeyou** [comment]
My bad
