### ISSUE TITLE
[Bug] Meteor Crashes On Startup with Bookdupe

### ISSUE THREAD

**Issue by wevans16736** [MeteorDevelopment/meteor-client#349]
**Describe the bug**
It was working fine beforehand, gave me an error and crashed upon launch when I installed bookdupe from the MeteorDevelopment github (release, not source)

**Expected behavior**
Meteor starts up with no issues and allows me to do .d and perform book dupes.

**Additional context**
Add any other context (meteor version 0.4.2, minecraft version 1.16.4, Hwyla, Sodium, Shulker Box Tooltip, Ok Zoomer, MaLiLib, Litematica, Grid 1.16.4, appleskin, fabric API).

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/25/21 5:42 PM
Description: Initializing game

java.lang.NoSuchMethodError: minegame159.meteorclient.commands.Command.<init>(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at meteordevelopment.addons.bookdupe.BookDupeCommand.<init>(BookDupeCommand.java:26)
	at meteordevelopment.addons.bookdupe.BookDupeAddon.onInitialize(BookDupeAddon.java:12)
	at minegame159.meteorclient.MeteorClient$$Lambda$3680/1144406463.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at minegame159.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:120)
	at net.minecraft.class_310.handler$zip004$onInit(class_310.java:6404)
	at net.minecraft.class_310.<init>(class_310.java:592)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.addons.bookdupe.BookDupeCommand.<init>(BookDupeCommand.java:26)
	at meteordevelopment.addons.bookdupe.BookDupeAddon.onInitialize(BookDupeAddon.java:12)
	at minegame159.meteorclient.MeteorClient$$Lambda$3680/1144406463.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at minegame159.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:120)
	at net.minecraft.class_310.handler$zip004$onInit(class_310.java:6404)
	at net.minecraft.class_310.<init>(class_310.java:592)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 860108800 bytes (820 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.3.1
		baritone: Baritone 1.6.3
		bookdupe-addon: Meteor Book Dupe Addon 0.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		grid: Grid 1.16.4-fabric0.25.1-1.6.3
		litematica: Litematica 0.0.0-dev.20201103.184101
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		meteor-client: Meteor Client 0.4.2
		minecraft: Minecraft 1.16.4
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		sodium: Sodium 0.1.0
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

-- Meteor Client --
Version: 0.4.2

```

**Comment by RedCarlos26** [comment]
Are you using the last dev build of meteor?

**Comment by seasnail8169** [comment]
No, they aren't. As i clearly state in my message, you **must** be using the latest dev build to avoid this crash.

**Comment by wevans16736** [comment]
> 
> 
> Are you using the last dev build of meteor?

If that's 0.4.2, yes. Got it like, 2 or 3 days ago.

**Comment by RedCarlos26** [comment]
No go check the dev-build channel on the meteor discord
