### ISSUE TITLE
[Bug] Instant Crash when joining world with sodium mod

### ISSUE THREAD

**Issue by realm2100** [MeteorDevelopment/meteor-client#3626]
### Describe the bug

Minecraft instantly crashes when joining a world with exit code -1.

### Steps to reproduce

```bash
Put latest meteor dev build (0.5.3-1835) and latest sodium release (0.4.11-1.19.4) into mods folder and join a world
```

### Meteor Version

0.5.3-1835

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by orsondmc** [comment]
Here's the crash report

```
[11:15:20] [Render thread/WARN]: Error loading class: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter (java.lang.ClassNotFoundException: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter)
[11:15:20] [Render thread/WARN]: Error loading class: net/caffeinemc/mods/sodium/api/vertex/attributes/CommonVertexAttribute (java.lang.ClassNotFoundException: net/caffeinemc/mods/sodium/api/vertex/attributes/CommonVertexAttribute)
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
Time: 2023-05-04 11:15:22
Description: Initializing game
java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.utils.render.MeshVertexConsumerProvider$MeshVertexConsumer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at meteordevelopment.meteorclient.utils.render.MeshVertexConsumerProvider.<init>(MeshVertexConsumerProvider.java:17)
	at meteordevelopment.meteorclient.systems.modules.render.StorageESP.<init>(StorageESP.java:156)
	at meteordevelopment.meteorclient.systems.modules.Modules.initRender(Modules.java:502)
	at meteordevelopment.meteorclient.systems.modules.Modules.init(Modules.java:89)
	at meteordevelopment.meteorclient.systems.Systems.add(Systems.java:56)
	at meteordevelopment.meteorclient.systems.Systems.init(Systems.java:41)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:115)
	at net.minecraft.class_310.handler$zok005$meteor-client$onInit(class_310.java:10048)
	at net.minecraft.class_310.<init>(class_310.java:683)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for meteor-client-sodium.mixins.json:MeshVertexConsumerMixin from mod meteor-client during activity: [Transform -> Method push(Lorg/lwjgl/system/MemoryStack;JILnet/caffeinemc/mods/sodium/api/vertex/format/VertexFormatDescription;)V -> GETSTATIC -> net/caffeinemc/mods/sodium/api/vertex/attributes/CommonVertexAttribute::POSITION:Lnet/caffeinemc/mods/sodium/api/vertex/attributes/CommonVertexAttribute;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.attributes.CommonVertexAttribute
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 30 more
Caused by: java.lang.ClassNotFoundException: net.caffeinemc.mods.sodium.api.vertex.attributes.CommonVertexAttribute
	... 34 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at meteordevelopment.meteorclient.utils.render.MeshVertexConsumerProvider.<init>(MeshVertexConsumerProvider.java:17)
	at meteordevelopment.meteorclient.systems.modules.render.StorageESP.<init>(StorageESP.java:156)
	at meteordevelopment.meteorclient.systems.modules.Modules.initRender(Modules.java:502)
	at meteordevelopment.meteorclient.systems.modules.Modules.init(Modules.java:89)
	at meteordevelopment.meteorclient.systems.Systems.add(Systems.java:56)
	at meteordevelopment.meteorclient.systems.Systems.init(Systems.java:41)
	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:115)
	at net.minecraft.class_310.handler$zok005$meteor-client$onInit(class_310.java:10048)
	at net.minecraft.class_310.<init>(class_310.java:683)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Mac OS X (aarch64) version 13.3.1
	Java Version: 17.0.7, Homebrew
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Homebrew
	Memory: 140761112 bytes (134 MiB) / 815792128 bytes (778 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1 Ultra
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.23
	Number of physical packages: 1
	Number of physical CPUs: 20
	Number of logical CPUs: 20
	Graphics card #0 name: Apple M1 Ultra
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: Display Firmware Version: Version 16.4 (Build 20E246), Display Firmware Version: Version 16.4 (Build 20E246)
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 131072.00
	Virtual memory used (MB): 65492.91
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.5.3-1835
			baritone-meteor: Baritone 1.19.4-SNAPSHOT
		minecraft: Minecraft 1.19.4
		nc: N 1.19.4-16
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.14.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.14.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.14.0
			com_github_collarmc_collar_api: api 91a4850864
			com_github_collarmc_collar_rest: rest 91a4850864
		owo: oωo 0.10.3+1.19.4
			blue_endless_jankson: jankson 1.2.2
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		viabackwards: ViaBackwards 4.6.1
		viafabric: ViaFabric 0.4.9+null-main
			org_yaml_snakeyaml: snakeyaml 1.33
			viafabric-mc119: ViaFabric for 1.19 0.4.9+null-main
		viaversion: ViaVersion 4.6.2
		xaerominimap: Xaero's Minimap 23.3.2
	Launched Version: 1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Apple M1 Ultra GL version 4.1 Metal - 83.1, Apple
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 20x Apple M1 Ultra
-- Meteor Client --
Version: 0.5.3
Dev Build: 1835
```

**Comment by orsondmc** [comment]
This seems to work fine with latest version of sodium for 1.19.4. I propose we close this issue.

https://modrinth.com/mod/sodium/version/mc1.19.4-0.4.11

**Comment by Wide-Cat** [comment]
@orsondmc are you another account of @realm2100? If not, then @realm2100 please send a crash report.

**Comment by realm2100** [comment]
Seems the issue was actually with the Sodium Extras mod, fixed with the latest release.

**Comment by lidzard** [comment]
I have this issue
