### ISSUE TITLE
[Bug] Instant Crash when using Java 16 AdoptOpenJDK

### ISSUE THREAD

**Issue by PepeHands78** [MeteorDevelopment/meteor-client#388]
**Describe the bug**
Instant Crash when using Java 16 (AdoptOpenJDK):

openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

**To Reproduce**
1. Install meteor-client-0.4.2-658.jar (latest commit) + fabric-api-0.32.5+1.16 (latest fabric API) to mods
2. Start Minecraft
3. Crash

**Expected behavior**
No Crash

**Additional context**
Crash log:

---- Minecraft Crash Report ----
// You're mean.

Time: 4/1/21, 2:54 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "this.executor" is null
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:77)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:27)
	at net.minecraft.class_310.handler$zdf000$onPreTick(class_310.java:6914)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by PepeHands78** [comment]
Additional info: It appears Gradle 6.6.1 (which is used as of the time of writing this issue) does not support Java 16 yet: https://github.com/gradle/gradle/issues/13629

Probably best to wait tackling this issue till Gradle 7 is released and adopted by the project.

**Comment by MineGame159** [comment]
Fixed
