### ISSUE TITLE
NoFall crash

### ISSUE THREAD

**Issue by FinLemonKe** [MeteorDevelopment/meteor-client#4154]
### Steps to reproduce

Caused by: java.lang.ClassCastException: class net.minecraft.class_2827 cannot be cast to class meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor (net.minecraft.class_2827 and meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @63753b6d)
	at meteordevelopment.meteorclient.systems.modules.movement.NoFall.onSendPacket(NoFall.java:124) ~[meteor-client-0.5.5-1949.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.5-1949.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61) ~[meteor-client-0.5.5-1949.jar:?]
	at net.minecraft.class_2535.handler$cci000$meteor-client$onSendPacketHead(class_2535.java:3751) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10743(class_2535.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_8673.method_52787(class_8673.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.redirect$bhf000$lemon-client$sendPacketFull(class_746.java:2884) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_3136(class_746.java:275) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:229) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	... 16 more

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/MRhhdBb

### Meteor Version

Meteor 4152

### Minecraft Version

MC 1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
That is not the complete crash log, please send the full one.
Also, I have no idea how you managed to pu 4152 as the Meteor version, since that doesn't exist.
