### ISSUE TITLE
Nuker Crash

### ISSUE THREAD

**Issue by ImNotStable** [MeteorDevelopment/meteor-client#4231]
### Steps to reproduce

Activated nuker via keybind

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://pastebin.com/9jycyyf4

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by ImNotStable** [comment]
I can't reproduce it as just activated Nuker and it happened, but it's on the latest dev build

**Comment by ImNotStable** [comment]
Got it again while activating timer

```

Unreported exception thrown!
java.lang.IndexOutOfBoundsException: Index (265) is greater than or equal to list size (100)
	at it.unimi.dsi.fastutil.ints.IntArrayList.removeInt(IntArrayList.java:359)
	at net.minecraft.class_338.handler$djc000$meteor-client$onAddMessage(class_338.java:2152)
	at net.minecraft.class_338.method_1815(class_338.java)
	at net.minecraft.class_338.method_44811(class_338.java:211)
	at net.minecraft.class_338.method_1812(class_338.java:206)
	at net.minecraft.class_338.meteor$add(class_338.java:2106)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:144)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:126)
	at meteordevelopment.meteorclient.utils.player.ChatUtils.sendMsg(ChatUtils.java:121)
	at meteordevelopment.meteorclient.systems.modules.Module.sendToggledMsg(Module.java:91)
	at meteordevelopment.meteorclient.systems.modules.Modules.onAction(Modules.java:273)
	at meteordevelopment.meteorclient.systems.modules.Modules.onKey(Modules.java:259)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:61)
	at net.minecraft.class_309.handler$dlk000$meteor-client$onKey(class_309.java:2118)
	at net.minecraft.class_309.method_1466(class_309.java)
	at net.minecraft.class_309.method_22678(class_309.java:486)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:486)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1300)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by ImNotStable** [comment]
Crash Report: https://mclo.gs/uGZBpUx

**Comment by Wide-Cat** [comment]
😩 not more anti spam stuff

**Comment by ImNotStable** [comment]
?

**Comment by ImNotStable** [comment]
I KEEP CRASHING
