### ISSUE TITLE
[Bug] BlockESP Error

### ISSUE THREAD

**Issue by bruh1273** [MeteorDevelopment/meteor-client#4305]
### Describe the bug

The BlockESP module throws an error in console.

### Steps to reproduce

1. Enabled BlockESP
2. Added some blocks
3. Checked console and saw errors

```
[17:06:38] [Meteor-Executor-105/ERROR]: Uncaught exception in thread "Meteor-Executor-105"
net.minecraft.class_148: Getting block state
	at net.minecraft.class_2818.method_8320(class_2818.java:191) ~[client-intermediary.jar:?]
	at meteordevelopment.meteorclient.systems.modules.render.blockesp.ESPChunk.searchChunk(ESPChunk.java:101) ~[meteor-client-0.5.6-1987.jar:?]
	at meteordevelopment.meteorclient.systems.modules.render.blockesp.BlockESP.lambda$searchChunk$1(BlockESP.java:162) ~[meteor-client-0.5.6-1987.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.class_6558: Missing Palette entry for index 0.
	at net.minecraft.class_2814.method_12288(class_2814.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12331(class_2841.java:158) ~[client-intermediary.jar:?]
	at net.minecraft.class_2841.method_12321(class_2841.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2826.method_12254(class_2826.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_8320(class_2818.java:183) ~[client-intermediary.jar:?]
	... 5 more
```

### Meteor Version

0.5.6-1987

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by 19MisterX98** [comment]
Do you have any other mods that could potentially mess with chunks?

**Comment by bruh1273** [comment]
> Do you have any other mods that could potentially mess with chunks?

Yes, I have Nvidium, Sodium, and Bobby installed; This may be the root of the problem.

**Comment by bewf** [comment]
> > Do you have any other mods that could potentially mess with chunks?
> 
> Yes, I have Nvidium, Sodium, and Bobby installed; This may be the root of the problem.

By change, how did you get meteor client to work with sodium? it would not work for me no matter what
