### ISSUE TITLE
[Bug] BetterTooltips crashes with REI

### ISSUE THREAD

**Issue by bartaback** [MeteorDevelopment/meteor-client#432]
When searching items in the REI mod interface (https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) the game crash
Uninstallling/disabling the meteor client fix the issue so i think it's a conflict between some new meteor modules and REI

Crash log

Time: 4/7/21 6:09 PM
Description: Unexpected error

java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1584)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at me.shedaniel.rei.api.ClientHelper.appendModIdToTooltips(ClientHelper.java:197)
	at me.shedaniel.rei.impl.ItemEntryStack.getTooltip(ItemEntryStack.java:292)
	at me.shedaniel.rei.impl.SearchArgument.tryGetEntryStackTooltip(SearchArgument.java:180)
	at me.shedaniel.rei.impl.search.TooltipArgument.matches(TooltipArgument.java:71)
	at me.shedaniel.rei.impl.search.TooltipArgument.matches(TooltipArgument.java:42)
	at me.shedaniel.rei.impl.SearchArgument.matches(SearchArgument.java:176)
	at me.shedaniel.rei.impl.SearchArgument.canSearchTermsBeAppliedTo(SearchArgument.java:164)
	at me.shedaniel.rei.gui.widget.EntryListWidget.canLastSearchTermsBeAppliedTo(EntryListWidget.java:559)
	at me.shedaniel.rei.gui.widget.EntryListWidget.lambda$updateSearch$6(EntryListWidget.java:511)
	at me.shedaniel.rei.gui.widget.EntryListWidget$$Lambda$5302/1374358527.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	... 5 more

Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Meteor Client --
Version: 0.4.2
Dev Build: 696

[Render]:
Better Tooltips (better-tooltips)
Entity Owner (entity-owner)
HUD (HUD)
No Render (no-render)
Unfocused Cpu (unfocused-cpu)

[Misc]:
Vanilla Spoof (vanilla-spoof)

i can try to reproduce it with meteor and REI only ?

**Comment by MineGame159** [comment]
Did you confirm it only happens with Meteor?

**Comment by MineGame159** [comment]
Also try disabling Better Tooltips, that might be whats crashing it.

**Comment by bartaback** [comment]
It's the Better Tooltips module, some options crash the game (not the shulker preview it seems but other options in the Better Tooltips crash the game)

it's Meteor client related, without it no bugs

**Comment by MineGame159** [comment]
Works with latest REI
