### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jvideo-sk** [MeteorDevelopment/meteor-client#4347]
### Describe the bug

Game wont run on 1.20.2
Error:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-01-21 14:45:23
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.get(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null
	at net.minecraft.class_338.getBetterChat(class_338.java:1232)
	at net.minecraft.class_338.handler$zof000$meteor-client$onRefresh(class_338.java:1225)
	at net.minecraft.class_338.method_44813(class_338.java)
	at net.minecraft.class_338.method_1817(class_338.java:301)
	at net.minecraft.class_1041.handler$bfp000$recode$rescaleSideChat(class_1041.java:521)
	at net.minecraft.class_1041.method_15997(class_1041.java:390)
	at net.minecraft.class_310.method_15993(class_310.java:1400)
	at net.minecraft.class_310.<init>(class_310.java:640)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Steps to reproduce

1. Download the most recent version of Fabric 1.20.2
2. Run the game

### Meteor Version

Meteor 0.5.5

### Minecraft Version

MC 1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send the whole crash report

**Comment by jvideo-sk** [comment]
Whole Crash Report:
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-01-21 14:51:42
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.get(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null
	at net.minecraft.class_338.getBetterChat(class_338.java:1232)
	at net.minecraft.class_338.handler$zof000$meteor-client$onRefresh(class_338.java:1225)
	at net.minecraft.class_338.method_44813(class_338.java)
	at net.minecraft.class_338.method_1817(class_338.java:301)
	at net.minecraft.class_1041.handler$bfp000$recode$rescaleSideChat(class_1041.java:521)
	at net.minecraft.class_1041.method_15997(class_1041.java:390)
	at net.minecraft.class_310.method_15993(class_310.java:1400)
	at net.minecraft.class_310.<init>(class_310.java:640)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_338.getBetterChat(class_338.java:1232)
	at net.minecraft.class_338.handler$zof000$meteor-client$onRefresh(class_338.java:1225)
	at net.minecraft.class_338.method_44813(class_338.java)
	at net.minecraft.class_338.method_1817(class_338.java:301)
	at net.minecraft.class_1041.handler$bfp000$recode$rescaleSideChat(class_1041.java:521)
	at net.minecraft.class_1041.method_15997(class_1041.java:390)
	at net.minecraft.class_310.method_15993(class_310.java:1400)
	at net.minecraft.class_310.<init>(class_310.java:640)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.2506:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.23.0:
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Setup API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2861 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna14753159638283627588.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Microsoft Color Matching System DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:30.0.14.7247:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wldp.dll:Windows Lockdown Policy:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 506992568 bytes (483 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.41
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7247
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19258.08
	Virtual memory used (MB): 13584.78
	Swap memory total (MB): 2944.00
	Swap memory used (MB): 86.11
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone-meteor: Baritone 1.20.2-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.3.0
		elementa: Elementa 619
		essential: Essential 1.3.0.2+ge922acc4a7
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		fabric-api: Fabric API 0.91.4+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.80+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.10+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.4+3fe0ff24a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.13+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.11+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.46+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.12+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		meteor-client: Meteor Client 0.5.5
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.1
		nbteditor: NBT Editor 1.12.3
		org_jetbrains_annotations: annotations 13.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		recode: recode 0.1.0-beta.9+1.20.2-LATEST
			adventure-platform-fabric: adventure-platform-fabric 5.10.0
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.3
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloth-config: Cloth Config v12 12.0.109
				cloth-basic-math: cloth-basic-math 0.6.1
			javax_websocket_javax_websocket-api: javax.websocket-api 1.1
			libgui: LibGui 9.2.0+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		universalcraft: UniversalCraft 323
		vigilance: Vigilance 295
	JVM uptime in seconds: 22.601
	Launched Version: fabric-loader-0.15.6-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.47, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

-- Meteor Client --

Version: 0.5.5
```
Other Mods Installed:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/59378133/885d813b-f3c3-478e-b854-b18e35216c2c)

**Comment by RacoonDog** [comment]
mod compat issue, probably essential if i had to guess

**Comment by jvideo-sk** [comment]
It only gives an error when I put in Meteor Client 1.20.2

**Comment by GreemDev** [comment]
> It only gives an error when I put in Meteor Client 1.20.2

yes, do you understand what "compatibility" means
