### ISSUE TITLE
It didn't even open the game.

### ISSUE THREAD

**Issue by Panpan0single** [MeteorDevelopment/meteor-client#4440]
### Steps to reproduce

The only mod I have is meteor-client-0.5.6
Maybe my system that cause the Crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

[11:22:07] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7 [11:22:08] [main/INFO]: Loading 6 mods: 	- fabricloader 0.15.7 	   \-- mixinextras 0.3.5 	- java 17 	- meteor-client 0.5.6-2027 	   \-- fabric-resource-loader-v0 0.11.17+707e4d1b4f 	- minecraft 1.20.4 [11:22:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/acer/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT [11:22:08] [main/INFO]: Compatibility level set to JAVA_17 [11:22:09] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand) [11:22:09] [main/WARN]: @Mixin target baritone.command.defaults.ComeCommand was not found meteor-client-baritone.mixins.json:ComeCommandMixin from mod meteor-client [11:22:10] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). [11:22:11] [main/WARN]: COM exception querying Win32_Processor, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:11] [main/WARN]: COM exception querying Win32_Processor, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:11] [main/WARN]: COM exception querying Win32_VideoController, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:11] [main/WARN]: COM exception querying Win32_PhysicalMemory, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:19] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 319 milliseconds [11:22:23] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services] [11:22:23] [Render thread/ERROR]: Mixin apply for mod meteor-client failed meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching <init>(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)V in com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService for meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService; [INJECT Applicator Phase -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService;] org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching <init>(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)V in com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService for meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService; [INJECT Applicator Phase -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService;] 	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:120) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:103) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5] 	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[Ca.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createMinecraftSessionService(YggdrasilAuthenticationService.java:91) ~[authlib-6.0.52.2.jar:?] 	at net.minecraft.class_310.<init>(class_310.java:461) ~[client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?] [11:22:23] [Render thread/WARN]: COM exception querying Win32_Processor, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:23] [Render thread/WARN]: COM exception querying Win32_Processor, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:23] [Render thread/WARN]: COM exception querying Win32_VideoController, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422) [11:22:23] [Render thread/WARN]: COM exception querying Win32_PhysicalMemory, which might not be on your system. Will not attempt to query it again. Error was -2147023838: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.(HRESULT: 80070422)

### Meteor Version

meteor-client-0.5.6

### Minecraft Version

Fabric 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
> Link to crash report.
> Dumps the whole thing here as raw text.

Anyways... From this log I'll go on a wild guess and say you're using TLauncher (or some other cracked launcher).
We do not support those, as they edit the MC code and cause incompatibilities, along with the fact that we don't provide any help to cracked users, as said in our FAQ.
