### ISSUE TITLE
minecraft dont opens

### ISSUE THREAD

**Issue by isidoro123123** [MeteorDevelopment/meteor-client#4472]
### Describe the bug

idkPicked up _JAVA_OPTIONS: 
[14:42:01] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.7
[14:42:01] [main/INFO]: Loading 6 mods:
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- meteor-client 0.5.5
	   \-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	- minecraft 1.20.2
[14:42:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/USUARIO/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:42:01] [main/INFO]: Compatibility level set to JAVA_16
[14:42:01] [main/INFO]: Compatibility level set to JAVA_17
[14:42:02] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand)
[14:42:02] [main/WARN]: @Mixin target baritone.command.defaults.ComeCommand was not found meteor-client-baritone.mixins.json:ComeCommandMixin from mod meteor-client
[14:42:02] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.2.0).
[14:42:09] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 208 milliseconds
[14:42:12] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services]
[14:42:12] [Render thread/ERROR]: Mixin apply for mod meteor-client failed meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching <init>(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)V in com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService for meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService; [INJECT Applicator Phase -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching <init>(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)V in com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService for meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService; [INJECT Applicator Phase -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService;]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:120) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:103) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createMinecraftSessionService(YggdrasilAuthenticationService.java:91) ~[authlib-5.0.50.1.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:448) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:214) ~[Fabric%201.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-03-23 14:42:12
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createMinecraftSessionService(YggdrasilAuthenticationService.java:91)
	at net.minecraft.class_310.<init>(class_310.java:448)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client] from phase [DEFAULT] in config [meteor-client.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 14 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching <init>(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)V in com/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService for meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService; [INJECT Applicator Phase -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client -> Apply Accessors ->  -> Locate -> meteor-client.mixins.json:YggdrasilMinecraftSessionServiceAccessor from mod meteor-client->@Invoker[OBJECT_FACTORY]::createYggdrasilMinecraftSessionService(Lcom/mojang/authlib/yggdrasil/ServicesKeySet;Ljava/net/Proxy;Lcom/mojang/authlib/Environment;)Lcom/mojang/authlib/yggdrasil/YggdrasilMinecraftSessionService;]
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:120)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:103)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createMinecraftSessionService(YggdrasilAuthenticationService.java:91)
	at net.minecraft.class_310.<init>(class_310.java:448)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:API base de Windows 32 avanzado:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Biblioteca de controles de la experiencia del usuario:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DLL de API de cliente DNS:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:API auxiliar para IP:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Archivo DLL de cliente API BASE de Windows NT:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Archivo DLL de cliente API BASE de Windows NT:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24020.7 (f5b7a53876c03330b0e7c1a6020590269cbbc2b6):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE para Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Archivo DLL auxiliar del perfil de energía:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Ayudante de los datos de rendimiento DLL de Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Tiempo de ejecución de llamada a procedimiento remoto:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Archivo DLL común del shell de Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Archivo DLL de cliente API USER de Windows multiusuario:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Servicios HTTP de Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:DLL de 32 bits de Windows Socket 2.0:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Biblioteca de primitivas criptográficas de Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM para Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:Servicio cliente DHCP:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:Cliente DHCPv6:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:API de modo usuario de FWP/IPsec:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna8458292184660434028.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Proveedor de servicios de Microsoft Windows Sockets 2.0:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Proveedor de correcciones de compatibilidad (shim) de nomenclaturas de correo electrónico:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:DLL del nivel de Windows NT:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL de objetos de rendimiento del sistema Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:Proveedor de espacio de nombres PNRP:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Biblioteca de utilidades de Shell:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:API de almacenamiento de Microsoft WinRT:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:DLL de tipos basados en Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1035742376 bytes (987 MiB) / 1342177280 bytes (1280 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14741.60
	Virtual memory used (MB): 11160.09
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 444.98
	JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms1279M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	JVM uptime in seconds: 14.849
	Launched Version: Fabric 1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: es_AR
	CPU: <unknown>

-- Meteor Client --

Version: 0.5.5

#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\USUARIO\AppData\Roaming\.tlauncher\legacy\Minecraft\game\crash-reports\crash-2024-03-23_14.42.12-client.txt

### Steps to reproduce

i launched minecraft

### Meteor Version

1.20.2

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by isidoro123123** [comment]
doesnt happen when i use the 1.20 version

**Comment by Big-Iron-Cheems** [comment]
1. The issue template clearly states to post a link to th uploaded crash log, and not just paste it here raw (this is unreadable)
2. You're using TLauncher, and our FAQ says clearly that we do not provide any support to cracked users.
3. For context, this crash is caused exactly by your cracked launcher. If you want this to not happen, buy the game and use one ofr the supported launchers listed in our FAQ.

**Comment by Nekiplay** [comment]
Dont use TLauncher
