### ISSUE TITLE
Proxies don't work

### ISSUE THREAD

**Issue by jiscaskalov** [MeteorDevelopment/meteor-client#4562]
### Describe the bug

Proxies don't work and time out when you try to join a server. I have tried tens of different proxies from ProxyScrape and SocksList, and none seem to work.

![image](https://github.com/MeteorDevelopment/meteor-client/assets/94760971/ff85db36-d784-428b-8e28-16945f5b505a)
This is a valid proxy from SocksList in New Jersey.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/94760971/d9493892-fa0e-440a-a5c4-0a24f7926165)

Error:
```
[20:35:35] [Server Connector #1/ERROR]:
 Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: getsockopt: /104.236.0.129:17322
Caused by: java.net.ConnectException: Connection timed out: getsockopt
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Steps to reproduce

1. Create a proxy (socks4 or 5 doesn't matter)
2. Join a server

### Meteor Version

0.5.7-2073

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by jiscaskalov** [comment]
nvm this was already reported
