### ISSUE TITLE
[Bug] game crash when going down

### ISSUE THREAD

**Issue by chicacos** [MeteorDevelopment/meteor-client#4606]
### Describe the bug

whenever I fly straight down (no efly) or go down alot with efly in speeds higher than 1 my gane just crashes

### Steps to reproduce

![image](https://github.com/MeteorDevelopment/meteor-client/assets/111707367/65293e68-41c6-43eb-aa8f-b0d1de074811)

### Meteor Version

0.6.5-2007

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
send logs

**Comment by chicacos** [comment]
> send logs

[11:27:00] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index -2111664 out of bounds for length 37
	at net.minecraft.class_3508.method_15211(class_3508.java:187) ~[client-intermediary.jar:?]
	at net.minecraft.class_2902.method_12601(class_2902.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_2902.method_12603(class_2902.java:158) ~[client-intermediary.jar:?]
	at meteordevelopment.meteorclient.utils.entity.DamageUtils.fallDamage(DamageUtils.java:117) ~[meteor-client-0.5.6-2007.jar:?]
	at meteordevelopment.meteorclient.utils.player.PlayerUtils.possibleHealthReductions(PlayerUtils.java:219) ~[meteor-client-0.5.6-2007.jar:?]
	at meteordevelopment.meteorclient.systems.modules.combat.AutoTotem.onTick(AutoTotem.java:89) ~[meteor-client-0.5.6-2007.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.6-2007.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53) ~[meteor-client-0.5.6-2007.jar:?]
	at net.minecraft.class_310.handler$cgb000$meteor-client$onPreTick(class_310.java:20829) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[11:27:01] [Render thread/INFO]: Stopping worker threads
[11:27:01] [Render thread/INFO]: Started 1 worker threads
[11:27:01] [Render thread/INFO]: Saving
[11:27:01] [Render thread/INFO]: Saved in 84 milliseconds.
[11:27:01] [Render thread/INFO]: Minimap session finalized.
[11:27:01] [Render thread/INFO]: Finalizing world map session...
[11:27:01] [Thread-21/INFO]: World map cleaned normally!
[11:27:02] [Render thread/INFO]: World map session finalized.
[11:27:02] [Render thread/INFO]: Stopping worker threads
[11:27:03] [Thread-39/INFO]: [STDOUT]: saving seeds...
[11:27:03] [Thread-40/INFO]: Saving
