### ISSUE TITLE
Crash after pressing hotkey 

### ISSUE THREAD

**Issue by ItzSkyReed** [MeteorDevelopment/meteor-client#4738]
### Describe the bug

https://mclo.gs/8hbeidy
something wrong with sending chat alert about turning on/off module (in my case AutoWalk)

### Steps to reproduce

Play a lot, leave from server, load in and press any hotkey. For me it works something like that

### Meteor Version

0.5.8-2125

### Minecraft Version

1 21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ItzSkyReed** [comment]
Hm, I think there is an issue on conflict with https://modrinth.com/mod/chatpatches because I've got this error after loading in next time 
```
[23:06:54] [Render thread/ERROR] (Chat Patches) [ChatLog.deserialize] Tried to read the chat log and found an error, backing it up and loading an empty one:
java.lang.ClassCastException: class java.util.ArrayList$SubList cannot be cast to class java.util.ArrayList (java.util.ArrayList$SubList and java.util.ArrayList are in module java.base of loader 'bootstrap')
	at obro1961.chatpatches.chatlog.ChatLog.deserialize(ChatLog.java:155) ~[chatpatches-210.6.5.1.jar:?]
	at obro1961.chatpatches.ChatPatches.lambda$onInitializeClient$5(ChatPatches.java:55) ~[chatpatches-210.6.5.1.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$2(ClientPlayConnectionEvents.java:50) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-c561690eb32f01e.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.onServerReady(ClientPlayNetworkAddon.java:60) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-c561690eb32f01e.jar:?]
	at net.minecraft.class_634.handler$bkl000$fabric-networking-api-v1$handleServerPlayReady(class_634.java:4044) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```
