### ISSUE TITLE
Crash on Tick modules and Notifier

### ISSUE THREAD

**Issue by Johnsmith927** [MeteorDevelopment/meteor-client#4885]
### Steps to reproduce

1. Run minecraft 1.21 with meteor
2. Join server
3. Either crash during loading terrain or crash while in server
4. In logs, crash because of On Tick modules (ive crashed because of NoFall.onTick, Flight, and Logout Spots, ive crashed usually to NoFall but a couple times to Flight and once to Logout Spots)
5. Also in logs, crash because of the Falling Sand entity with Notifier

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/L2sixxy

### Meteor Version

Meteor 0.5.8

### Minecraft Version

1.21

### Operating System

macOS

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Johnsmith927** [comment]
The only things I had enabled in Notifier was totem pops, when an entity left or came into my render distance (I only had Player enabled), and pearl. It's not a huge issue to turn this off, but there's also the crash with the .OnTick ones

**Comment by Johnsmith927** [comment]
Just happened again, this time both NoFall.OnTick and Velocity.OnPacketRecieve. I wasn't falling or taking any damage or water push, I was just standing on one block, not moving, mining blocks. 
https://mclo.gs/fMnMXry

**Comment by RacoonDog** [comment]
try removing not enough crashes

**Comment by Johnsmith927** [comment]
I removed not enough crashes, and it was working well, but then it crashed again. NoFall.onSendPacket

Caused by: java.lang.ClassCastException: class net.minecraft.class_8590 cannot be cast to class meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor (net.minecraft.class_8590 and meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @551bdc27)
	at meteordevelopment.meteorclient.systems.modules.movement.NoFall.onSendPacket(NoFall.java:127) ~[meteor-client-0.5.8-2116.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.8-2116.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:67) ~[meteor-client-0.5.8-2116.jar:?]

**Comment by Wide-Cat** [comment]
send the whole log

**Comment by Johnsmith927** [comment]
https://mclo.gs/CgNUaaX

**Comment by Wide-Cat** [comment]
That log has a bunch of information truncated and its filled with network errors. Can you send another log thats more readable and has all the necessary information. Latest.log
